### ISSUE TITLE
Balance tab: minor changes

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#1044]
States of chart overview 
- No rate (before downloading data)
- Current Rate 
- Error ( data error )

**Comment by TalgatNurdinov** [comment]
<img width="724" alt="Screen Shot 2019-09-09 at 10 12 18 AM" src="https://user-images.githubusercontent.com/42367908/64502880-6890a180-d2ea-11e9-99aa-3129ca8be992.png">


https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=1481%3A3259
