### ISSUE TITLE
use our own library for interacting with keychain

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#1080]
- [ ] Currently we are using external library for interacting with iOS keychain, but we are going to use our own implementation soon for security reasons.
- [ ] work with Android team oaths together.

**Comment by ealymbaev** [comment]
I have fully reviewed 'KeychainAccess' pod that we are currently using for accessing iOS keychain. It does not do any external interactions and has a limited functionality to only work with keychain.

https://github.com/kishikawakatsumi/KeychainAccess

We can copy source code (only one file is used) to our repo, thus losing any updates, OR we can simply review source code every time we update this pod.

**Comment by esengulov** [comment]
> I have fully reviewed 'KeychainAccess' pod that we are currently using for accessing iOS keychain. It does not do any external interactions and has a limited functionality to only work with keychain.
> 
> https://github.com/kishikawakatsumi/KeychainAccess
> 
> We can copy source code (only one file is used) to our repo, thus losing any updates, OR we can simply review source code every time we update this pod.

let's keep fit then and review their updates with every release
