### ISSUE TITLE
Settings >> Report >> App Status

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#1111]
- [ ] Settings >> Report :  add "App Status" standalone cell above the existing two entires at the top (email/telegram). @Dianaaiym, localizable element

- [ ] Settings >> Report :  display following text above the "App Status" cell. Having problems with the app? Let us know below. To speed things up please send us some generic data about your app that you can copy from App Status section below. @Dianaaiym, localizable element

- [ ] App Status screen should display following data on the screen. The elements on the App Status page are not going to be localizeable.

App Status:

- time: timestamp
- version: x.y.z
- device: Samsung A1
- Android OS: x.y.z
- installed: Jan 2nd, 2019
- installed version: x.y.z
- update 1: version x.y.z
- update 2:  version x.y.z
... 

Blockchain Status:

- Bitcoin
-- synced until Jul 2nd, 2019
-- wallet type: BIP44 / BIP49
-- restored: true/false
-- peer 1 status:
-- peer 2 status:
-- ...

- Bitcoin Cash
-- synced until Jul 2nd, 2019
-- restored: true/false
-- peer 1 status:
-- peer 2 status:
--  ...

- Dash
-- disabled

- Ethereum
-- synced until Jul 2nd, 2019
-- restored: true/false
-- RPC host: infura
-- Transactions history: ....

- EOS
-- synced until Jul 2nd, 2019
-- restored: true/false
-- RPC host: infura

- Binance DEX
-- synced until Jul 2nd, 2019
-- restored: true/false
-- RPC host:

**Comment by ealymbaev** [comment]
1. What is the purpose of getting current timestamp?
2. Wallet type should not be here. It should be in the list of "wallet"s. It would be better to get the list of wallets from the user (account type, account settings (bip and before/after for Unstoppable key))
3. Install date should be replaced by "First launch date" I guess
4. "wallet: new / restored" should be related to "wallet", not app itself

**Comment by TalgatNurdinov** [comment]
<img width="812" alt="Screen Shot 2019-10-03 at 4 31 55 PM" src="https://user-images.githubusercontent.com/42367908/66119837-54934380-e5fb-11e9-86fd-8ff7859d0cb2.png">

https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=3467%3A539

**Comment by esengulov** [comment]
@mNizhurin  

- [ ] wallet new/restored not shown in the wallets list
