### ISSUE TITLE
Active pending indicator for PENDING transactions

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#1119]
- [x] At the moment we display static pending icon on pending transactions. The purpose of this issues  is to change static icon to an animated one .
- [x] for incoming transactions: Instead of "Processing" show "Receiving"
- [x] for outgoing transactions:  Instead of "Processing" show "Sending"

**Comment by TalgatNurdinov** [comment]
<img width="377" alt="Screen Shot 2019-10-23 at 2 04 06 PM" src="https://user-images.githubusercontent.com/42367908/67371375-1d7ed500-f59e-11e9-8d25-d37d427c950e.png">

https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=3713%3A1355

**Comment by TalgatNurdinov** [comment]
https://figmotion-renderer.freighter.studio/videos/3792:666:dbc45116-5b46-45eb-8a67-3ffa80086700-fdcb901f-3fac-4619-ab1d-e02c22f1ca66.gif

**Comment by esengulov** [comment]
@mNizhurin added two minor points, see the first comment
