### ISSUE TITLE
show alert when user tries to send to his own account

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#1129]
for all coins

**Comment by TalgatNurdinov** [comment]
<img width="381" alt="Screen Shot 2019-11-19 at 1 58 41 PM" src="https://user-images.githubusercontent.com/42367908/69127600-bab52680-0ad4-11ea-8e92-aa620fef476d.png">

**Comment by esengulov** [comment]
This issues was dropped from the list due to lack of team consensus on the importance/need of the described feature. We are already showing to the user indicator that transaction was sent to his/her own address.
