### ISSUE TITLE
UI Improvements for Balance Tab

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#1130]
minor layout edits for cells

**Comment by TalgatNurdinov** [comment]
<img width="855" alt="Screen Shot 2019-10-09 at 10 27 42 AM" src="https://user-images.githubusercontent.com/42367908/66451787-c0ecc780-ea7f-11e9-95f5-ea86345babdf.png">
https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=2975%3A18
