### ISSUE TITLE
UI Improvements for Prices on Lock Screen

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#1149]
- [x] prices 
-- do not show cent values for prices below 1000. values should be rounded
- [x] swap font sizes and placements for % price change and price amount
- [x]  instead of +/- symbols use up/down arrows (will be provided)
- [x] next to title show "x min/hours ago" (as an indicator of when the rates were synced last)

**Comment by TalgatNurdinov** [comment]
<img width="380" alt="Screen Shot 2019-10-03 at 3 47 39 PM" src="https://user-images.githubusercontent.com/42367908/66116783-2ad71e00-e5f5-11e9-8d6b-e4e43d6c3d20.png">

https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=3467%3A0

**Comment by TalgatNurdinov** [comment]
<img width="380" alt="Screen Shot 2019-10-30 at 12 12 30 PM" src="https://user-images.githubusercontent.com/42367908/67833330-90dc9580-fb0e-11e9-9295-4bc17bfaa875.png">
https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=3467%3A0
