### ISSUE TITLE
Handle Case When ERC20 token requires minimum amount on balance (ex: KuCoin)

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-ios#1181]
Certain tokens (mainly ERC20 at this point) require minimum amount to remain on the balance. As a result sending entire balance is not possible (https://etherscan.io/tx/0x98c1e67b6b7577317f2bc77a88853192688f1f57fa68cc05e73581b6d52b78f8)

Such cases need to bee handled accordingly:

- [x] send controller: when the balance amount for such token is below the min required amount we need to show an error "The minimum required balance for the KuCoin is 0.000x".
- [x] send controller: max button should not be shown
- [ ] @Dianaaiym the text above need to be localized

**Comment by ealymbaev** [comment]
I have reviewed failed transactions on KuCoin (both ours and other users') and it seems like transaction fails if user tries to send all his balance.
It may be an error in KuCoin contract code or some kind of limitation (protection).
This case requires more research.

**Comment by rafaelekol** [comment]
I talked with support on this site https://kucoin.zendesk.com.
They say that I should always keep minimum amount 0.001KCS when sending all balance. I asked for detailed information about this matter, but they didn't help with this. 
<img width="336" alt="2019-10-21_11-36-13" src="https://user-images.githubusercontent.com/1390965/67179103-1073b180-f3f7-11e9-8632-9c6b14cdf79c.png">
