### ISSUE TITLE
Send Controller: Available / Minimum Balance Protocol

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#1221]
- [x] proceed after following issue is completed https://github.com/horizontalsystems/unstoppable-wallet-ios/issues/1204. Check the implementation by trying to send the amount below the min. amount for BTC and BCH

- [x] Display available balance above amount input form in send controller. Refer to sigma for layout. We are basically adding an additional line which shows user amount available for spending.
- [x] Available Balance: The amount user is able to spend. It should take into account locked outputs if such exist as well as should ignore including dust outputs which are likely to have higher transaction cost then the actual value of the unspent.
-- for Bitcoin : Available = Total - Locked - Dust
- [x] Min. Amount: We a re adding a restriction on the minimum amount user is able to send. When the user enters an amount which is smaller than the min. allowed amount then the error that appears below the input form should say "min. value: 0.00000xyz"
- [x] in both cases where user enters the value above available balance or below the min. amount a respective error shown below the input form.

@Dianaaiym new texts were added.
- min. amount
- available balance
- min. required remainder

@TalgatNurdinov provide the layouts for all cases above

**Comment by TalgatNurdinov** [comment]
<img width="375" alt="Screen Shot 2019-10-31 at 3 12 09 PM" src="https://user-images.githubusercontent.com/42367908/67933848-da9dac80-fbf0-11e9-9254-e0d40004af6f.png">

**Comment by esengulov** [comment]
@Dianaaiym please move the ticket to accepted once the localized strings been added
