### ISSUE TITLE
Update Fee-rates provider for fee-rate-kit

### ISSUE THREAD

**Issue by nk-the-crazy** [horizontalsystems/unstoppable-wallet-ios#1222]
Update fee-rates provider for fee-rate-kit ( remove IPFS dependency).
Currently, fee-rates are provided from IPFS. This (IPFS) dependency should be removed and custom providers should be implemented as an alternative.  Fee-rates for BTC should be obtained from bitcoin-core-RPC and Infura.io API should be restored.

**Comment by mNizhurin** [comment]
This issue need to be updated. New fee rates kit became asynchronous and can throw errors. Thus we need new design to show progress of fetching, fail of fetching and maybe provide user with possibility to input custom rate.

**Comment by mNizhurin** [comment]
New btc node. Send controller need to be tested.
