### ISSUE TITLE
review predictive text behaviour on the Restore Key screens

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#1273]
When on. Restore Key screen the user is able to type only a few symbols and see the entire word in recommendations. In latest iOS this behavior changed slightly and now the recommendations include not just a single word but a sequence of them (if the user has entered these words before).

From security point of view we should configure it to the way it was previously and have predictive recommendations to include at most one word.

**Comment by mNizhurin** [comment]
Implement custom suggestion bar, using words from mnemonic dictionary

**Comment by esengulov** [comment]
> Decision was made to implement custom suggestion bar, using words from mnemonic dictionary in the next sprint. #1358
> For now - remove predictive input.

sounds good!
