### ISSUE TITLE
Different currency formatting on various devices

### ISSUE THREAD

**Issue by ealymbaev** [horizontalsystems/unstoppable-wallet-ios#1284]
On two devices that are both configured to English language app shows different formatting for currency values:

![IMG_0370](https://user-images.githubusercontent.com/377809/68654828-fbeb8a80-0558-11ea-921b-60dc1446bd77.PNG)
![IMG_2436](https://user-images.githubusercontent.com/377809/68654830-fbeb8a80-0558-11ea-954d-ddb442441808.PNG)

**Comment by esengulov** [comment]
@ealymbaev @ant013 this is an expected behavior as the screenshots were taken on the phone with different locales (Russia, United States)
