### ISSUE TITLE
Balance Tab : minor design improvement

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#1298]
both in collapsed/expanded coin cell: append coin type next to coin symbol

-- if token is on Ethereum  >> coin symbol (ERC20)
-- if token is on EOS >> coin symbol (EOS)
-- if token is on Binance DEX >> coin symbol (BEP2)

@TalgatNurdinov attach the designs

**Comment by TalgatNurdinov** [comment]
<img width="374" alt="Screen Shot 2019-11-15 at 12 06 50 PM" src="https://user-images.githubusercontent.com/42367908/68920783-98539e00-07a0-11ea-9761-5322edba465c.png">

https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=3553%3A70
