### ISSUE TITLE
Change Layout on Wallet Create/ restore pages

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#1313]
**Welcome >> Create New Wallet**

- [x] 'New Wallet' screen: list all tokens and allow multiple coin selection. 
- [x]  Add following text below the title.
> Select cryptocurrencies for the wallet. You will be able to add or remove coins later as well.
- [x] no coins should be selected by default. The coin list should be shown in alphabetical order, with the top section listing the primary tokens (BTC, BCH, DASH, ETH, Binance DEX, EOS)
- [x] display "blockchain" label next to tokens, like it's on balance tab.
-- ERC20 for Ethereum tokens
-- BEP2 for Binance tokens
-- EOSIO for EOS tokens
- [x] selected coins should appear on balance tab upon completion
- [x] if user tries to activate an EOS or any EOS based token show an error which tells that create not possible for EOS at this time.
- [x] if user selects BTC then show screen with address setting for the Bitcoin blockchain. 
-- page title: Bitcoin
-- that page should have one section: 'Address Format' should list BIP44/BIP49/BIP84.
-- text to display below the  'Address Format' section
> If you're creating a new wallet and not sure about this setting than select BIP49.
>
> If you're restoring an existing wallet with bitcoins on it then you should select the correct address type.
- [x] The BIP49 format should be preselected.
- [x] if user tries to activate any other token apart from EOS and Bitcoin, BCH, Dash then enable the coins without additional steps.

**Welcome >> Restore Wallet**

- [x] in the first screen that lists all wallet types, rename Unstoppable to Standard Wallet
- [x] next screen 'wallet_name' should list filtered list of coins depending on selection. 
--  screen title should be [wallet_name] wallet
-- If user selected EOS Wallet then only EOS and EOS based tokens should be shown, with a separator between EOS and other tokens.
-- If user selected Binance Wallet then only Binance DEX BNB and BEP2 tokens should be shown, with a separator between BNB and other tokens.
-- If user selected Standard Wallet then BTC, BCH, DASH, ETH and ERC20 tokens should be shown, with a separator between BTC, BCH, DASH, ETH and ERC20 tokens.
-- at least one coin ON selection is required before user may proceed to the next step.

- [x] when user restoring Standard Wallet >> BTC, BCH or DASH then show them screen with settings for the selected blockchain. 
-- page title: coin name (ex: Bitcoin, Bitcoin Cash or DASH)
-- (for Bitcoin) that page should have two sections: First section header 'Address Format' should list BIP44/BIP49/BIP84. Second section header 'Network Synchronization' for choosing initial sync mode for the blockchain. 
-- keep BIP 49 and FAST mode preselected.
-- (for BCH / DASH) that page should have just one section 'Network Synchronization' for choosing initial sync mode for the blockchain, with FAST mode preselected.
- [x] text to display below the  'Address Format' section
> If you're creating a new wallet and not sure about this setting than select BIP49.
>
> If you're restoring an existing wallet with bitcoins on it then you should select the correct address type.
- [x]  text to display below the 'Network Synchronization' section
> Fast: Restores wallet transaction history via secure third party server. Less private but fast.
>
> Slow:  Restores wallet transaction history directly from the blockchain. More private but very slow.

**Settings >> Manage Wallets**

- [x] 'wallet_type >> create' : title should be ''New Wallet"
- [x] 'wallet_type >>  restore' : title should be ''wallet_type" wallet
- [x] both for create/restore screen the text on top right button should be 'Next', not proceed
- [x] change 'below the title' text on the main screen
> Highlighted below are your active wallets where each wallet controls a set of cryptocurrencies.
>
> You must backup each highlighted wallet by backing up the private key for it. This key is the only way to restore and access your funds if your phone is ever lost, stolen or the app malfunctions.

**Coin Manager**

- [x] page title : Coin Manager
- [x] should display labels on all coins
- [x] when coin doesn't have an active key associated with it show the arrow ">" instead of there ON/OFF selector. Clicking on it would trigger create/restore bottom controller for the respective key.
- [x] apply text changes bottom controller which shown on activation of the coin that doesn't have an active key:
-- subtitle: add 'wallet' text string next to the [wallet_name] (ex: EOS Wallet)
> You need to set up [wallet_name] wallet to be able to send or receive [coin_name].
>
> Use the Create button below to set up a new [wallet_name] wallet, or Restore button to import the existing one.
>
> You will be able to use this wallet for: [supported_coins_tokens].

 
**Other Relevant changes**

- [x] adjust text on the 'Lock Bitcoins' controller. The second paragraph should say:
>The receiver of such transaction should use Unstoppable wallet  app version 0.10 or newer with BIP44 address format for the Bitcoin.

**@TalgatNurdinov** 

- [x] reattach new screenshots taking into account newly updated description text

**Comment by TalgatNurdinov** [comment]
https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=4102%3A357

<img width="638" alt="Screen Shot 2019-11-18 at 4 57 38 PM" src="https://user-images.githubusercontent.com/42367908/69047063-8bdf7780-0a24-11ea-92bc-f13149c6e755.png">

**Comment by TalgatNurdinov** [comment]
updated
<img width="650" alt="Screen Shot 2019-11-18 at 6 45 51 PM" src="https://user-images.githubusercontent.com/42367908/69053489-b38a0c00-0a33-11ea-856a-a66289d4e40f.png">

**Comment by TalgatNurdinov** [comment]
**NEW**

![Uploading Screen Shot 2019-11-22 at 4.06.51 PM.png…]()

**RESTORE FROM STANDARD**

<img width="1641" alt="Screen Shot 2019-11-22 at 4 07 15 PM" src="https://user-images.githubusercontent.com/42367908/69417143-4a134180-0d42-11ea-8efd-029f25e7260e.png">

**RESTORE FROM BINANCE / EOS**
<img width="703" alt="Screen Shot 2019-11-22 at 4 07 29 PM" src="https://user-images.githubusercontent.com/42367908/69417201-63b48900-0d42-11ea-8e17-1058383cfce9.png">

**Comment by TalgatNurdinov** [comment]
<img width="382" alt="Screen Shot 2019-11-22 at 5 04 32 PM" src="https://user-images.githubusercontent.com/42367908/69421033-2c49da80-0d4a-11ea-80dc-244ccbd67e90.png">

**Comment by esengulov** [comment]
@TalgatNurdinov seems you forgot labels on coin manager )
