### ISSUE TITLE
Timelocked & To self Transactions

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#1332]
- [x] When user sends a regular transaction to himself the amount should appear as is.
-- the message on tx info: This transaction was sent to your own address.

- [x] When user sends a locked transaction, transactions tab (and tx info) should display value as is (not 0) with lock sign next to amount on transactions tab

- [x] In both cases transactions should appear as outgoing payment.

- [x] on tx info for **all** timelocked transaction, display the locked date with hours. At the moment it just shows the date, month, year. Ex: Dec 19, 2019, 3 PM

**Comment by TalgatNurdinov** [comment]
<img width="373" alt="Screen Shot 2019-12-05 at 11 04 12 PM" src="https://user-images.githubusercontent.com/42367908/70256962-ac912680-17b3-11ea-804e-2ccd47f51926.png">
<img width="373" alt="Screen Shot 2019-12-05 at 11 04 23 PM" src="https://user-images.githubusercontent.com/42367908/70256963-ac912680-17b3-11ea-86cc-ed7af6e87c00.png">
https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=4386%3A1325
