### ISSUE TITLE
Implement custom suggestion bar, using words from mnemonic dictionary

### ISSUE THREAD

**Issue by mNizhurin** [horizontalsystems/unstoppable-wallet-ios#1358]
https://github.com/tomknig/TOMSSuggestionBar

**Comment by mNizhurin** [comment]
@TalgatNurdinov we need design for custom predictive field above keyboard.

**Comment by esengulov** [comment]
@mNizhurin @TalgatNurdinov when implemented it should work both on key input/restore and confirmation/backup screens
