### ISSUE TITLE
TX Fees Rate : Allow user to set custom fee rate

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#1416]
BTC 
- uses HS Bitcoin node to obtain recommended values for the present 
- fallbacks to hardcoded values

BCH / DASH
- use hardcoded values

ETH
- uses Infura to obtain recommended values for the present 
- fallbacks to hardcoded values

## to do

- [x] allow user to set custom fee

**Comment by TalgatNurdinov** [comment]
https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=7709%3A468

<img width="795" alt="Screen Shot 2020-03-30 at 2 16 49 PM" src="https://user-images.githubusercontent.com/42367908/77890320-1cf71280-7291-11ea-846b-6fa0f6a7caae.png">

**Comment by Dianaaiym** [comment]
app crashes on send Bitcoin
