### ISSUE TITLE
'Sort by Balance' works incorrect

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-ios#1422]
How to reproduce: open balance tab and make 'sort by balance'  or  at first make 'sort by name' and  then 'sort by balance'

if you make 'sort by 24h price (%)' and then 'sort by balance', it works correct

**Comment by esengulov** [comment]
![IMG_0720](https://user-images.githubusercontent.com/8611762/70966792-955d0d80-20be-11ea-9217-2b43da18a709.PNG)
![IMG_0721](https://user-images.githubusercontent.com/8611762/70966793-95f5a400-20be-11ea-993b-71c488fa7743.PNG)
