### ISSUE TITLE
All BTC block explorers show as offline when transaction hasn't reached the mempool

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-ios#1439]
BTC block explorers show as offline when accessed via Bitcoin TX Info >> Verify, if transaction hasn't reached the mempool. We need to show the full information

**Comment by TalgatNurdinov** [comment]
<img width="375" alt="Frame" src="https://user-images.githubusercontent.com/42367908/70994922-6adc7600-20f9-11ea-94dd-7e112150112e.png">
https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=4621%3A4584
