### ISSUE TITLE
Handle double spend transactions

### ISSUE THREAD

**Issue by omurovch** [horizontalsystems/unstoppable-wallet-ios#1474]
Currently double spend transactions, received from mempool, are not handled properly. Need to:

- show all double spend transactions received from mempool
- make first received double spend transaction "more valid", meaning that it will be used for calculation of wallet balance
- mark all conflicting transactions as "double spend" in GUI
- after one of the transactions "win" and is included in block, mark all other conflicting transactions as "failed"

**Comment by TalgatNurdinov** [comment]
@ant013 
- Need to remove attention icon from transactions list and from transaction info when it failed
- Text color should be Lucian

<img width="382" alt="Screen Shot 2020-01-10 at 2 47 50 PM" src="https://user-images.githubusercontent.com/42367908/72139787-8580d280-33b9-11ea-9a65-b40520a80507.png">
<img width="378" alt="Screen Shot 2020-01-10 at 2 47 40 PM" src="https://user-images.githubusercontent.com/42367908/72139789-86196900-33b9-11ea-9107-add41d9453ae.png">
