### ISSUE TITLE
Onboarding Improvements: Wallet Settings Redesign

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#1483]
See prototype on Figma, https://www.figma.com/proto/RDIKlTdIejA9cir83By3gS/Unstoppable-UX-Area?node-id=336%3A2661&viewport=1528%2C431%2C0.25&scaling=scale-down

## NEW WALLET USERS

Welcome >> New Wallet behavior

- [x] when user creates wallet we never show him/her [coin] settings screen. The wallet should be set up with default values: FAST SYNC (for all blockchains) and BIP49 address format for Bitcoin and Litecoin.
- [x] when the user disables [coin] the wallet should remember [coin] settings of the disabled coin and on reactivation auto-set to the previous values. Changing this would only be possible from Settings >> Manage Wallets >> Advanced Settings >> [coin] Settings. 

## RESTORED WALLET USERS

Welcome >> Restored Wallet behavior

- [x] the steps for restoring wallets should be in the following order: Welcome > Restore > Choose Wallet > Key > Coin Selector > [coin] Settings. 
- [x] the list coins that will show [coin] settings are: BTC, LTC. For Bitcoin and Litecoin the preselected settings are BIP49.
- [x] on Welcome >> Restore Wallet change title to 'Choose Wallet' and remove the description text below the title.
- [x] when the user reactivates the coin which was deactivated earlier s/he should again see [coin] settings. 

## SETTINGS / MANAGE WALLETS

- [x] rename Wallet Settings >> Manage Wallets
- [x] place Manage Wallets as the first item on settings page, above security settings
- [x] apply changes to Manage Wallets layout

### Manage Wallet >> Wallet Item >> Unlink

- [x] clicking on Unlink (in not backed up state) should show same alert controller that's shown on Coin >> Receive (in non backed up state)

### Manage Wallet >> Wallet Item >> Restore

- [x] restore steps: Restore > Key > Coin Selector > [coin] Settings

### Manage Wallet >> Standard Wallet >> Address Format

- [x] apply the layout for this screen
- [x] address format for Standard should display format for all activated coins. If the [coin] is not enabled then show format selector as inactive.
- [x] when user tries to change the address format for Bitcoin/ Litecoin show notification
> > After this change the wallet will have to resync itself with the [coin_name] blockchain. 
> >
> > When you change the address format for [coin_name] the current balance and transaction history will no longer be visible on balance tab. Changing it back to previous setting will bring everything back after the wallet resyncs itself with the blockchain. We recommend not to change it if not sure what that is.
> > Button 1 : Change to BIP 44/49/84 (depending on the setting)
> > Button 2: Cancel

- [x] do not show DONE button on top right as user already confirms the change in the previous alert. Done button only shown during restore where alert not shown.

## Other

- [x] EOS restore screen: remove ''enter your private key for EOS wallet'' text block
- [x] apply a new left padding on all cells

**Comment by TalgatNurdinov** [comment]
<img width="1371" alt="Screen Shot 2020-03-09 at 10 31 50 AM" src="https://user-images.githubusercontent.com/42367908/76183066-491ef680-61f1-11ea-8979-d864345b9654.png">
https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=4778%3A742
