### ISSUE TITLE
External Testing for Unstoppable users with TestFlight

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#1484]
Sample from Zap wallet: https://testflight.apple.com/join/elC3EXAK

We need same thing. As far as I recall in the past this was limited to 100/1000 users but I am not sure. regardless, get this in place and post the link here when done.

**Comment by Dianaaiym** [comment]
We can invite up to 10,000 testers using just their email address or by sharing a public link

Public link: (version 0.11) https://testflight.apple.com/join/kttjDgCd
