### ISSUE TITLE
BNB token send error: unknown error binancechain.kit.binancechainapiprovider..apierror.wrongtransaction

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#1497]
Experienced this error while trying to send BNB (Binance DEX). 

First three transfers went without issues, the fourth one returned the error above which persisted for about 12 hours and then disappeared (resolved itself).

Provide details regarding when this error is shown.

Based on the findings, if needed, create same issue for Android team

**Comment by esengulov** [comment]
![IMG_0849](https://user-images.githubusercontent.com/8611762/72326720-e79f4780-36d9-11ea-93dd-8e282e63abc9.PNG)

**Comment by ant013** [comment]
Bnb provider return transaction with ok=false status for broadcast. 
https://docs.binance.org/api-reference/dex-api/paths.html#apiv1broadcast
And no more information about this state.
