### ISSUE TITLE
tx info: display fiat value next to fee

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#1517]

**Comment by TalgatNurdinov** [comment]
![Transactions 25](https://user-images.githubusercontent.com/42367908/72799330-2f404900-3c6f-11ea-8f0d-dc28e9e858d7.png)
https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=5471%3A5731
