### ISSUE TITLE
coin charts: display latest coin news

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#1588]
Cryptocompare API provides an endpoint to get latest news for the asset.

We would like to have the latest news for the asset in the coin chart controller. 

- [x] For BTC, BCH, ETH, DASH, USDT use a quarry in the following format:

https://min-api.cryptocompare.com/data/v2/news/?categories=[coin_symbol], regulation&excludeCategories=Sponsored

- [x] For other currencies use

https://min-api.cryptocompare.com/data/v2/news/?categories=altcoin,trading,regulation&excludeCategories=Sponsored

- [x] Request 50 articles in each query. 
- [x] Set the expiration that would trigger new request to 30 minutes

**Comment by TalgatNurdinov** [comment]
<img width="826" alt="Screen Shot 2020-02-25 at 11 43 40 AM" src="https://user-images.githubusercontent.com/42367908/75218337-212c9d80-57c4-11ea-9b97-1ee7365ddf0f.png">
https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=6494%3A29207
