### ISSUE TITLE
Litecoin Infrastructure Setup

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#1600]
- [x] find block explorer (@esengulov )
- [x] setup fee service (@esengulov )
- [x] setup fast restore API (@nk-the-crazy )

**Comment by esengulov** [comment]
- [ ] for block explorer we can use https://blockchair.com/api/docs . Ideally we need another one as a fallback

- [ ] fee service

 curl -v --data-binary '{}' http://134.209.138.9/ltc/fee_low
 curl -v --data-binary '{}' http://134.209.138.9/ltc/fee_avg
 curl -v --data-binary '{}' http://134.209.138.9/ltc/fee_high
 curl -v --data-binary '{}' http://134.209.138.9/ltc/gbc
 curl -v --data-binary '{}' http://134.209.138.9/ltc/gbb

**Comment by esengulov** [comment]
@Dianaaiym please check this one and close issue if everything works as expected 

- fee service
- network restore
- api restore
- tx info >> litecoin tx block explorer

**Comment by Dianaaiym** [comment]
need to test
