### ISSUE TITLE
add Share button to tx info controller

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#1601]

**Comment by TalgatNurdinov** [comment]
Clicking on the transaction ID's copyist should open system share controller
(see in design group)

**Comment by TalgatNurdinov** [comment]
- [ ] Update hash copyist height 
<img width="614" alt="Screen Shot 2020-03-16 at 2 40 20 PM" src="https://user-images.githubusercontent.com/42367908/76738060-1a29f700-6794-11ea-9602-ade7445064c3.png">

**Comment by ant013** [comment]
Fixed
