### ISSUE TITLE
I have a issue when i build from xcode 11 on OSX Mojave

### ISSUE THREAD

**Issue by elohffa** [horizontalsystems/unstoppable-wallet-ios#1617]
I got following erro message, when I build the app on xcode , 
/GitHub/unstoppable-wallet-ios/BankWallet/BankWallet/Configuration/Bank Dev.debug.xcconfig:2: could not find included file 'Development.xcconfig' in search paths

**Comment by ealymbaev** [comment]
You need to have `Development.xcconfig` file for Debug configuration and `Production.xcconfig` file for Release in `BankWallet/BankWallet/Configuration`.
You can use sample configurations in `.template.xcconfig` files.
