### ISSUE TITLE
add option to hide balance

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#1622]
There will be a slightly visible button next to balance amount on Balance tab. Clicking on that should substitute all values for * symbols.

- this should apply top the values on balance tab and transactions tab.
- clicking on the icon in activated state (i.e. balance hidden) should deactivate the setting and reveal all values

@TalgatNurdinov will provide the design for the feature

**Comment by TalgatNurdinov** [comment]
![jidebalance](https://user-images.githubusercontent.com/42367908/76654321-efbe1b00-6594-11ea-97b5-027eac689ff6.gif)

**Comment by TalgatNurdinov** [comment]
updated 
<img width="789" alt="Screen Shot 2020-03-19 at 10 49 13 AM" src="https://user-images.githubusercontent.com/42367908/77032720-6d3bbe00-69cf-11ea-86d9-2bc5249b91fd.png">
