### ISSUE TITLE
add Synthetix token

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#1623]
Add new token to the app:

- [x] token image attached
- [x] rates and other data, https://www.cryptocompare.com/coins/snx/overview/USDT
- [x] get all data needed for chart view
- mkt cap
- in circulation
- total supply

**Comment by TalgatNurdinov** [comment]
asset icon added
<img width="149" alt="Screen Shot 2020-03-16 at 3 52 52 PM" src="https://user-images.githubusercontent.com/42367908/76744410-67ab6180-679e-11ea-96c9-7bcd8d6c937d.png">
