### ISSUE TITLE
tx info >> share button : should share the link to transaction page on block selected explorer

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#1624]
Currently the button triggers share for transaction ID string but should share the transaction page on selected block explorer

**Comment by ealymbaev** [comment]
Not all block explorers have web page for tx info. What should be shared in this case?

**Comment by esengulov** [comment]
> Not all block explorers have web page for tx info. What should be shared in this case?

If the page not available then I suggest either disabling (not showing) share button OR just copy the transaction ID

**Comment by ealymbaev** [comment]
The `selected block explorer` is related to `full tx info` only. `Simple tx info` is used for showing tx info based on our internally stored data, and should not be related to external block explorers. Thus linking user to some block explorer from here is not quite right.

**Comment by esengulov** [comment]
ok, consider it done then :)
