### ISSUE TITLE
display syncing indicator on Transactions tab when wallet is in syncing state (for any of the coins)

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#1625]

**Comment by TalgatNurdinov** [comment]
- On syncing state need display "Please wait for the sync to finish" and add spinner to top of screen.
- When transactions appears on screen remove text and show spinner while syncing
- If does'nt have any transaction show placeholder text "You don’t have any pending or past transactions yet"

<img width="1167" alt="Screen Shot 2020-03-19 at 5 38 13 PM" src="https://user-images.githubusercontent.com/42367908/77282267-a176ed80-6cf3-11ea-8298-7f1bcb4fd38b.png">
