### ISSUE TITLE
I have a issue when i build from xcode 11 on OSX Mojave #1617

### ISSUE THREAD

**Issue by texyz** [horizontalsystems/unstoppable-wallet-ios#1643]
I got following erro message, when I build the app on xcode ,
/GitHub/unstoppable-wallet-ios/BankWallet/BankWallet/Configuration/Bank Dev.debug.xcconfig:2: could not find included file 'Development.xcconfig' in search paths

**Comment by texyz** [comment]
Please I really need help pls

**Comment by esen** [comment]
Hey texyz,
Added "Installation" section in Readme file

[https://github.com/horizontalsystems/unstoppable-wallet-ios/tree/version/0.13#installation](https://github.com/horizontalsystems/unstoppable-wallet-ios/tree/version/0.13#installation)
