### ISSUE TITLE
Missing Path

### ISSUE THREAD

**Issue by texyz** [horizontalsystems/unstoppable-wallet-ios#1649]
Showing All Messages
/Users/josh/iosfinal/special/unstoppable-wallet-ios/BankWallet/BankWallet/Configuration/Bank.debug.xcconfig:2: could not find included file 'Production.xcconfig' in search paths

**Comment by ealymbaev** [comment]
You should have both `Development.xcconfig` and `Production.xcconfig` in `Configuration` directory.
For initial start you can simply copy them from `.template.xcconfig` files.
