### ISSUE TITLE
Manage Wallets screen >> Address Format

### ISSUE THREAD

**Issue by TalgatNurdinov** [horizontalsystems/unstoppable-wallet-ios#1666]
- [x] In Manage Wallets screen rename the Advanced Setting to Address Format. The Address Format screen should display the address setting for all blockchains where it' relevant. 

<img width="842" alt="Screen Shot 2020-03-31 at 2 54 18 PM" src="https://user-images.githubusercontent.com/42367908/78006992-82b1d000-735f-11ea-9502-f7a4e91f615b.png">

- [ ] Left padding of the cells and headers from 24px to 16
- [ ] Add multiline description for Wallets header cell

**Comment by mNizhurin** [comment]
last two tasks moved to #1675
