### ISSUE TITLE
balance tab: handle click on sync error/exclamation icon shown on coin cell

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#1679]
- [x] change header text on Privacy Screen from "Blockchain Connection" to "Blockchain Sync" @Dianaaiym 
- [x] change Source should be shown for all tokens/blockchains except Binance Chain (+tokens) and EOS(+tokens)

**Comment by TalgatNurdinov** [comment]
<img width="407" alt="Screen Shot 2020-04-30 at 5 13 38 PM" src="https://user-images.githubusercontent.com/42367908/80704590-ae62da00-8b06-11ea-8a18-9515ddc3cff6.png">

https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=9433%3A3474
