### ISSUE TITLE
Disable auto-scanning of Face/Touch ID when app is locked

### ISSUE THREAD

**Issue by ealymbaev** [horizontalsystems/unstoppable-wallet-ios#1704]
- add button to numbed for triggering touch/face ID.
- the button icon should be displayed according to iPhone - face or touch id

**Comment by Dianaaiym** [comment]
the button icon should be displayed according to iPhone - face or touch id

**Comment by Dianaaiym** [comment]
Now on iPhone 10 (where there is a face id), the touch id icon is displayed

![2020-04-21 16 16 39](https://user-images.githubusercontent.com/22589457/79855077-487ea000-83ec-11ea-9d06-34ff2f5d87e2.jpg)
