### ISSUE TITLE
Implement ActiionSheetController with fully custom view

### ISSUE THREAD

**Issue by ealymbaev** [horizontalsystems/unstoppable-wallet-ios#1706]
New ActionSheetController should be able:

- to work in "bottom action sheet" and "center alert" modes
- to work with custom view and table/collection views (especially with SectionsTableView)
- it should not use its own items and view items

**Comment by TalgatNurdinov** [comment]
changes on selector font (subhead 2)
https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=8888%3A4479
