### ISSUE TITLE
Use seeds instead of words for mnemonic Account Types

### ISSUE THREAD

**Issue by abdrasulov** [horizontalsystems/unstoppable-wallet-ios#1804]
As for now, we store words for mnemonic account types. Every time when bitcoin kit is initialized it converts words to seed that takes time. It is better to store seeds instead of words.

**Comment by ealymbaev** [comment]
Seed cannot be converted back to words, so we cannot store seed only. Storing both words and seed is not required for iOS as seed generation does not take much time.
