### ISSUE TITLE
Guides tab

### ISSUE THREAD

**Issue by ealymbaev** [horizontalsystems/unstoppable-wallet-ios#1821]
1. Create Guide model with the following fields:
- title
- image (url)
- coin (optional)
- blocks - list of various blocks (headers, paragraph, image, quote, lists)

2. Implement controller for Guides list according to design

UICollectionView should be used for the list of guides, as some rows display single guide item, and some display two items.

**Comment by TalgatNurdinov** [comment]
last version 
https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=10515%3A13

**Comment by TalgatNurdinov** [comment]
- [ ] Add placeholder icon on not downloaded images 
- [ ] Rename tab to Academy @Dianaaiym
