### ISSUE TITLE
Errors not localized:

### ISSUE THREAD

**Issue by mNizhurin** [horizontalsystems/unstoppable-wallet-ios#1831]
- [x]  mnemonic validation (wrong eos key, more than 12 words)
- [x]  eos self transfer, no ram

**Comment by Dianaaiym** [comment]
![2020-05-20 17 53 07](https://user-images.githubusercontent.com/22589457/82443144-d1a7f600-9ac2-11ea-99da-c9a4fe75ea35.jpg)

not localizable error
