### ISSUE TITLE
apply new graphics on welcome screens

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#1864]

**Comment by TalgatNurdinov** [comment]
- [ ] Image area is placed at the height of 70% of the screen (currently 50%)
- [ ] replace images and circle

<img width="670" alt="Screen Shot 2020-05-28 at 10 12 56 AM" src="https://user-images.githubusercontent.com/42367908/83098442-767e9080-a0cc-11ea-950a-e68c7d2e5b00.png">
https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=8928%3A2295

**Comment by TalgatNurdinov** [comment]
![knoledge@2x](https://user-images.githubusercontent.com/42367908/83407085-d14c1b00-a431-11ea-9557-e27cb3788a7d.png)
![knoledge@3x](https://user-images.githubusercontent.com/42367908/83407096-d315de80-a431-11ea-8eb7-0d9a33ce1cce.png)
