### ISSUE TITLE
Extract Data hex constructor to UIExtensions to remove duplicate code from kits

### ISSUE THREAD

**Issue by mNizhurin** [horizontalsystems/unstoppable-wallet-ios#2013]

**Comment by Dianaaiym** [comment]
when sending erc20, two transactions appear: 1) tx erc20 2) tx eth
![2020-08-13 12 06 55](https://user-images.githubusercontent.com/22589457/90099988-8453c180-dd5d-11ea-8a1a-a4a344c110d5.jpg)

**Comment by Dianaaiym** [comment]
tested
