### ISSUE TITLE
add styling to App Status

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#2074]
- [x] add UI
- [ ] watched wallets show origin as restored, should be "watched wallet"

**Comment by TalgatNurdinov** [comment]
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?type=design&node-id=76620-193111&mode=design&t=J5TaBDEfdXaDTqvI-11
