### ISSUE TITLE
Uniswap UI Enhancements

### ISSUE THREAD

**Issue by TalgatNurdinov** [horizontalsystems/unstoppable-wallet-ios#2092]
- [x] Add description of approving to bottom sheet

- [x] Instead spinner of approving fee, show "loading..."

- [ ] Remove the spinner from the allowance value, make it "gray 50" until we get the value on swap screen

https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=20622%3A0

**Comment by ant013** [comment]
Instead spinner from the allowance value, show "loading..." too
