### ISSUE TITLE
design advanced settings for Uniswap swap controller

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#2129]
Refer to settings and options available on Uniswap's Settings page. We need a place to add following settings somewhere:

-  price slippage : there is a default option, as well as other presets.

- deadline setting to specify validity period for the swap

- option to select the swap beneficiaries which is different from the address of the sender

Errors:

slippage settings:

- [ ] if user tries to enter an amount lower than 0.01% then show 'Your transaction is likely to fail.'
- [ ] if user tries to enter an amount higher than 20% then show 'Max. allowed value 20%.'

**Comment by TalgatNurdinov** [comment]
<img width="826" alt="Screen Shot 2020-10-07 at 11 43 10" src="https://user-images.githubusercontent.com/42367908/95291920-4d4be900-0892-11eb-9f82-f18a8ce4b435.png">

https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=22338%3A0
