### ISSUE TITLE
sync/connection error for Ethereum

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#2229]
When app remains in background for extended period of time Ethereum and ERC20 tokens show disconnected alert while other coins sync without issues.

Looks like a connectivity issue with the socket. 

- pull to refresh doesn't do anything
- internet on/off fixes the issues
- killing the app and reopening the app again fixes the issue

**Comment by esen** [comment]
Got `NSOSStatusErrorDomain` -> `errSSLClosedAbort(-9806)` error
