### ISSUE TITLE
Mnemonic generator doesn't check return value of SecRandomCopyBytes

### ISSUE THREAD

**Issue by defuse** [horizontalsystems/unstoppable-wallet-ios#2326]
I noticed an issue while reviewing the mnemonic library, [this call to SecRandomCopyBytes](https://github.com/horizontalsystems/hd-wallet-kit-ios/blob/3e3720f600d10929146e5e8583cf39a072b37e61/HdWalletKit/Classes/Mnemonic.swift#L34), which is used to generate a mnemonic seed, does not have its return value checked before the bytes are used as a seed.

Without checking the return value (it should be `errSecSuccess` if the call succeeded), it's possible for the random number generator to fail in some way, resulting in the wallet using a weak seed.

(Interestingly, the [Android code](https://github.com/horizontalsystems/hd-wallet-kit-android/blob/41d5525df2ab64bbcd1bb4ac8a0cdb0713193aa7/src/main/kotlin/io/horizontalsystems/hdwalletkit/Mnemonic.kt#L24-L25) doesn't have this problem, as there's [no return value or exceptions to check for](https://developer.android.com/reference/kotlin/java/security/SecureRandom#nextBytes(kotlin.ByteArray)) so presumably it's designed to not ever fail)

**Comment by esen** [comment]
[The next line](https://github.com/horizontalsystems/hd-wallet-kit-ios/blob/3e3720f600d10929146e5e8583cf39a072b37e61/HdWalletKit/Classes/Mnemonic.swift#L37) does exactly what you are suggesting. `withUnsafeMutableBytes` returns what `SecRandomCopyBytes` returns. Then it is checked before the bytes are used.

**Comment by defuse** [comment]
Oh, my bad! Sorry for the invalid report!
