### ISSUE TITLE
Sending to domain address

### ISSUE THREAD

**Issue by kansalt** [horizontalsystems/unstoppable-wallet-ios#2329]
- Address input should be editable for entering fio (unstoppable.crypto).
- Also need the spinner for validating after entering name.
- Error should be shown same as like invalid address

https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0-Unstoppable-Design-System?node-id=9319%3A178

**Comment by Dianaaiym** [comment]
remove placeholder 'Domain' on send module for Zcash
