### ISSUE TITLE
Implement renBTC bridge

### ISSUE THREAD

**Issue by ealymbaev** [horizontalsystems/unstoppable-wallet-ios#2397]

**Comment by esengulov** [comment]
- coordinate implementation steps with @ealymbaev 

Successful implementation of this feature would provide bidrectional swap for following pairs:

- BTC to renBTC
- BCH to renBCH
- ZEC to renZEC

**Comment by esengulov** [comment]
This issues was dropped from the list due to lack of team consensus on the importance/need of the described feature
