### ISSUE TITLE
Not able to get the Production.xcconfig & Development.xcconfig file

### ISSUE THREAD

**Issue by mca14012021** [horizontalsystems/unstoppable-wallet-ios#2406]
We are not able to get these 2 files could you please let me know how we can get this

**Comment by ealymbaev** [comment]
It is documented in Readme file:

https://github.com/horizontalsystems/unstoppable-wallet-ios/blob/master/README.md

2. You need to have `Development.xcconfig` file for Debug configuration and `Production.xcconfig` file for Release in `UnstoppableWallet/UnstoppableWallet/Configuration`.
You can use sample configurations in `.template.xcconfig` files.
