### ISSUE TITLE
Add more fiat currencies to base currency list

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-ios#2411]
such as
- AUD
- CAD
- SGD

**Comment by Dadybayo** [comment]
### Popular 
AUD - Australian Dollar 
EUR - Euro 
GBP - British Pound 
USD - US Dollar 
BTC - Bitcoin 
ETH - Ethereum 
BNB - BNB 

### All
AED - United Arab Emirates Dirham
AFN - Afghan Afghani
ALL - Albanian Lek 
AMD - Armenian Dram 
ANG - Netherlands Antillean Guilder 
AOA - Angolan Kwanza 
ARS - Argentine Peso 
AWG - Aruban Florin 
AZN - Azerbaijani Manat 
BAM - Bosnia-Herzegovina Convertible Mark 
BBD - Barbadian Dollar 
BDT  - Bangladeshi Taka 
BGN - Bulgarian Lev 
BHD - Bahraini Dinar 
BIF - Burundian Dollar 
BND - Brunei Dollar 
BMD - Bermudan Dollar 
BOB - Bolivian Boliviano 
BRL - Brazilian Real 
BSD - Bahamian Dollar 
BTN - Bhutanese Ngultrum 
BWP - Botswanan Pula 
BYN - Belarusian Ruble 
BZD - Belize Dollar 
CAD - Canadian Dollar 
CDF - Congolese Franc 
CHF - Swiss Franc 
CLP - Chilean Peso 
CNY - Chinese Yuan 
COP - Colombian Peso 
CRC - Costa Rican Colon 
CUP - Cuban Peso 
CVE - Cape Verdean Escudo 
CZK - Czech Koruna 
DJF - Djiboutian Franc 
DKK - Danish Krone 
DOP - Dominican Peso 
DZD - Algerian Dinar 
EGP - Egyptian Pound 
ERN - Eritrean Nakfa 
ETB - Ethiopian Birr
FJD - Fijian Dollar 
FKP - Falkland Islands Pound 
GEL - Georgian Lari 
GHS - Ghanainan Cedi 
GIP - Gibraltar Pound 
GMD - Gambian Dalasi 
GNF - Guinean Franc 
GTQ - Guatemalan Quetzal
GYD - Guyanese Dollar 
HKD - Hong Kong Dollar 
HNL - Honduran Lempira 
HRK - Croatian Kuna 
HTG - Haitian Gourde 
HUF - Hungarian Forint 
IDR - Indonesian Rupiah 
ILS - Israeli New Shekel
INR - Indian Rupee
IQD - Iraqi Dinar 
IRR - Iranian Rial 
ISK - Icelandic Krona 
JMD - Jamaican Dollar 
JOD - Jordanian Dinar 
JPY - Japanese Yen 
KES - Kenyan Shilling 
KGS - Kyrgyzstani Som 
KHR - Cambodian Riel 
KMF - Comorian Franc 
KPW - North Korean Won 
KRW - South Korean Won 
KWD - Kuwaiti Dinar 
KYD - Cayman Islands Dollar 
KZT - Kazakhstani Tenge 
LAK - Laotian Kip 
LBP - Lebanese Pound 
LKR - Sri Lankan Rupee
LRD - Liberian Dollar 
LYD - Libyan Dinar 
MAD - Moroccan Dirham 
MDL - Moldovan Leu 
MGA - Malagasy Ariary 
MKD - Macedonian Denar 
MMK - Myanmar Kyat 
MNT - Mongolian Tugrik 
MOP - Macanese Pataca 
MUR - Mauritian Rupee
MVR - Maldivian Rufiyaa 
MWK - Malawian Kwacha 
MXN - Mexican Peso 
MYR - Malaysian Ringgit 
MZN - Mozambican Metical 
NAD - Namibian Dollar 
NGN - Nigerian Dollar 
NIO - Norwegian Krone 
NRP - Nepalese Rupee 
NZD - New Zealand Dollar 
OMR - Omani Rial 
PAB - Panamanian Balboa 
PEN - Peruvian Sol 
PGK - Papua New Guinean Kina 
PHP - Philippine Piso 
PKR - Pakistani Rupee 
PLN - Polish Zloty 
PYG - Paraguayan Guarani 
QAR - Qatari Rial 
RON - Romanian Leu 
RUB - Russian Ruble
RSD - Serbian Dinar 
RWF - Rwandan Franc 
SAR - Saudi Riyal 
SBD - Solomon Islands Dollar 
SCR - Seychellois Rupee 
SDG - Sudanese Pound 
SEK - Swedish Krona 
SGD - Singapore Dollar 
SHP - St. Helena Pound 
SLL - Sierra Leonean Leone 
SOS - Somali Shilling 
SRD - Surinamese Dollar 
SYP - Syrian Pound 
SZL - Swazi Lilangeni 
THB - Thai Baht 
TJS - Tajikistani Somoni 
TMT - Turkmenistani Somoni 
TND - Tunisian Dinar 
TOP - Tongan Pa'anga 
TRY - Turkish Lira 
TTD - Trinidad & Tobago Dollar 
TWD - New Taiwan Dollar 
TZS - Tanzanian Shilling 
UAH - Ukrainian Hryvnia 
UGX - Ugandan Shilling 
UYU - Uruguayan Peso 
UZS - Uzbekistani Som
VES - Venezuelan Bolivar 
VND - Vietnamese Dong 
VUV - Vanuatu Vatu 
WST - Samoan Tala 
XAF - Central African CFA Franc 
XCD - East Caribbean Dollar 
XOF - West African CFA Franc
XPF - CFP Franc 
YER - Yemeni Rial 
ZAR - South African Rand 
ZMW - Zambian Kwacha

**Comment by Dadybayo** [comment]
The changes will only affect the balance tab @Dianaaiym

**Comment by Dadybayo** [comment]
### We need to add the following fiat currencies to base currency list 

AUD - Australian Dollar

CAD - Canadian Dollar

SGD - Singapore Dollar

BRL - Brazilian Real

CHF - Swiss Franc

CNY - Chinese Yuan

HKD - Hong Kong Dollar

ILS - Israeli New Shekel

RUB - Russian Ruble

TRY - Turkish Lira

@Dianaaiym

**Comment by TalgatNurdinov** [comment]
@Dianaaiym
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0-Unstoppable-Design-System?node-id=9433%3A3053

**Comment by Dadybayo** [comment]
Popular 

- AUD 
- EUR 
- USD 
- BTC
- ETH 
- BNB

All 
- ~~~

**Comment by kansalt** [comment]
New layouts
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0-Unstoppable-Design-System?node-id=33844%3A0
