### ISSUE TITLE
Bitcoin Cash wallets has preFork coin type in Address derivation path

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-ios#2417]
***BitcoinCashKit***

Add ability to provide `coin type` in constructor. It should accept enum with two cases (0 and 145).

***Application***

- when restoring BitcoinCash wallet - user should be prompted to select desired `coin type` in bottom sheet (just like BIP for Bitcoin)
- this setting should be stored in database and shown in `Address Format` page in settings

**Comment by esengulov** [comment]
Texts:

title: Address Fromat
subtitle: Bitcoin Cash

option 1
- title: Legacy
- text: Older wallets (before Aug 2017)

option 1
- title: New
- text: Newer wallets
