### ISSUE TITLE
implement device root detection

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#2418]
This was a recommendation from a security audit. Refer to the last point in the audit document for the potential ways to address the issue.

**Comment by TalgatNurdinov** [comment]
Need to block the app with this screen when device root detected

<img width="375" alt="image" src="https://user-images.githubusercontent.com/42367908/103643926-b0c3e080-4f7f-11eb-8b49-0d70274a3095.png">
