### ISSUE TITLE
get xrates for all bep2 and bep20 token from binance

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-ios#2419]
- [ ] The price of BTC and BTCB (Bep2) are different

**Comment by Dianaaiym** [comment]
![Uploading 2020-12-15 15.10.06.jpg…]()

**Comment by Dianaaiym** [comment]
![2020-12-15 15 10 06](https://user-images.githubusercontent.com/22589457/102194647-c3e71180-3ee7-11eb-8285-be183914eeb1.jpg)

**Comment by ant013** [comment]
We get all rates from coinGecko for now. For each one (BTC, BTC-bep20, WrappedBtc) coinGecko has different ids and returns different values. We can't  merge it into one coinType
