### ISSUE TITLE
Localize errors

### ISSUE THREAD

**Issue by mNizhurin** [horizontalsystems/unstoppable-wallet-ios#2438]
Project:
```
    enum TransactionError: Error {
        case insufficientBalance(requiredBalance: BigUInt)
    }

```
Ethereum kit:
```
    public enum EstimatedLimitError: Error {
        case insufficientBalance
    }

```

these are shown in wallet connect request controller

**Comment by mNizhurin** [comment]
![IMAGE 2021-01-05 16:34:40](https://user-images.githubusercontent.com/1726387/103636242-e8c52680-4f73-11eb-8ddc-5ff334696546.jpg)

**Comment by Dianaaiym** [comment]
![2021-01-04 18 20 48](https://user-images.githubusercontent.com/22589457/103636614-7274f400-4f74-11eb-926b-3ddc0322ce11.jpg)
