### ISSUE TITLE
Bitcoin fee and available balance is error when total balance is smaller than fee

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-ios#2529]
In send bitcoin view, bitcoin fee and available balance are both zero when total balance is smaller than fee, when debug it, found throw SendValueErrors$Dust exception. The expected results is available balance view is zero and fee view display the correct fee value.

The ethereum send view is correct.

**Comment by esen** [comment]
Closed in Android version. Discussin in https://github.com/horizontalsystems/unstoppable-wallet-android/issues/3110
