### ISSUE TITLE
markets tab: coin page

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#2617]
- [x]  for UI questions consult @kansalt 
- [x] certain sections will not be shown when data not available i.e. coin rating, coin markets etc
- [x] data that will be shown in About section will be taken from JSON file. For questions contact @Dadybayo or @esengulov
- [x]  for data that is shown above the About section contact @nk-the-crazy

**Comment by TalgatNurdinov** [comment]
coin page design:
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0-Unstoppable-Design-System?node-id=28151%3A153795

**Comment by TalgatNurdinov** [comment]
**New Changes:** 

- [ ] Use Image icons for markets cells
- [ ] Add Investors page
- [ ] Need to change charts of volume and indicators, their should be overlayed on the price chart
