### ISSUE TITLE
ZCash: transaction with max value doesn't change status on sending device.

### ISSUE THREAD

**Issue by ant013** [horizontalsystems/unstoppable-wallet-ios#2669]

**Comment by gmale** [comment]
Note: the fixes for this have been merged into the Rust libraries that are used by the SDKs. We are planning SDK releases next week that will include these fixes and others.

https://github.com/zcash/librustzcash/issues/356#issuecomment-805513550
https://github.com/zcash/librustzcash/pull/359
https://github.com/zcash/librustzcash/pull/360
