### ISSUE TITLE
missing auto change address for BTC and forks

### ISSUE THREAD

**Issue by sebastianpulido** [horizontalsystems/unstoppable-wallet-ios#2673]
Hello,
I am sure you are aware, just to highlight that that bitcoin.org recommends changing BTC address after each transaction, in order to improve privacy.

Trust Wallet has this option in the privacy section. I am sure it would be a nice feature to add to the wallet.

**Comment by Dianaaiym** [comment]
> Hello,
> I am sure you are aware, just to highlight that that bitcoin.org recommends changing BTC address after each transaction, in order to improve privacy.
> 
> Trust Wallet has this option in the privacy section. I am sure it would be a nice feature to add to the wallet.

Hi,

Unstoppable has this option too. Once a public address receives an incoming payment, a new address will automatically be generated and display when you click on Receive.
