### ISSUE TITLE
Not all of the top 10 cryptocurrencies (by market cap) are supported by this wallet

### ISSUE THREAD

**Issue by sebastianpulido** [horizontalsystems/unstoppable-wallet-ios#2674]
Hello,
I noticed that ADA, DOT and others (DOGE) are not supported yet by the wallet.

It would be a great feature for the wallet.

Thanks

**Comment by Dianaaiym** [comment]
> Hello,
> I noticed that ADA, DOT and others (DOGE) are not supported yet by the wallet.
> 
> It would be a great feature for the wallet.
> 
> Thanks

Hi,

Thank you for the feedback!
We are working on tasks to add blockchains such as Avalanche/Polkadot/Monero. We plan to integrate in upcoming updates.

Subscribe to us on social media and support our wallet

Reddit - https://reddit.com/r/UNSTOPPABLEWallet/

Telegram - https://t.me/unstoppable_announcements

Medium - https://medium.com/@unstoppablewallet
