### ISSUE TITLE
Add cells to the "Coin page"

### ISSUE THREAD

**Issue by kansalt** [horizontalsystems/unstoppable-wallet-ios#2685]
<img width="1390" alt="Screen Shot 2021-03-04 at 2 18 09 PM" src="https://user-images.githubusercontent.com/58926737/109935667-04407980-7cf8-11eb-8647-6dd9a260c016.png">

- [x] Replace the name in the title with the coin code (1)
- [x] Add a cell for the name of the coin (2) and for its rank (3)

<img width="1407" alt="Screen Shot 2021-03-04 at 2 19 00 PM" src="https://user-images.githubusercontent.com/58926737/109935773-115d6880-7cf8-11eb-9d67-5d488dde5f2f.png">

- [x] Add a cell for the function "Read More"

**Comment by mNizhurin** [comment]
pr's are here: #2617
