### ISSUE TITLE
Show PIN unlock for screens with sensitive informations

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#274]
- [x] Backup screen. This shouldn't accept FaceID/TouchID/Fingerprint, even if it's activated the PIN should be requested. The same lockout logic as for app unlock should be applied here
- [ ] Unlink from this device. This shouldn't accept FaceID/TouchID/Fingerprint, even if it's activated the PIN should be requested. The same lockout logic as for app unlock should be applied here.
- [x] on Face ID activation

**Comment by mNizhurin** [comment]
No reason for pin unlock on unlink, coz user can reinstall the app.
