### ISSUE TITLE
Add ability to show release notes and important points to users after update

### ISSUE THREAD

**Issue by ealymbaev** [horizontalsystems/unstoppable-wallet-ios#2811]
On the first launch after app update we can show some kind of alert that will show:

- release notes, new notable changes in features and UI/UX
- important notes, e.g. dropping support of some features or OS versions

**Comment by esengulov** [comment]
keep a log of all release notes in Settings >> About app. User should be able to browse all release notes we published so far from that section. It can be added manually on each release on grabbed from Github (needs to be decided).

**Comment by esengulov** [comment]
@TalgatNurdinov design needed here as well as for respective iOS issue

**Comment by TalgatNurdinov** [comment]
In the settings page I suggest only showing release notes of installed release.
(Next time we'll think about how to display release notes of older versions)

<img width="408" alt="Screen Shot 2021-04-05 at 18 16 30" src="https://user-images.githubusercontent.com/42367908/113573036-2bfa6880-963b-11eb-9ae9-86161b2ed73d.png">

The release notes should use the same styles as the academy guides

<img width="406" alt="Screen Shot 2021-04-05 at 18 16 55" src="https://user-images.githubusercontent.com/42367908/113573093-43d1ec80-963b-11eb-88c5-4a611bf9f537.png">

when opened for the first time after an update, the release notes are displayed with the "Close" button.

<img width="408" alt="Screen Shot 2021-04-05 at 18 17 14" src="https://user-images.githubusercontent.com/42367908/113573155-6106bb00-963b-11eb-94b6-dfd1c08bc9c0.png">

https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0-Unstoppable-Design-System?node-id=27712%3A497
