### ISSUE TITLE
Coin Manager UI redesign 

### ISSUE THREAD

**Issue by kansalt** [horizontalsystems/unstoppable-wallet-ios#2831]
- [x] Replace the "Title" header component on the page
- [x] Replace the coin's cells components 
- [x] Remove the "Choose Blockchain" state (Add Token)
- [x] Implement new layouts for "Add Token" page

https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0-Unstoppable-Design-System?node-id=31658%3A271781

**Comment by TalgatNurdinov** [comment]
These improvements will be implemented in the next sprints (keep in mind)

- The search results must include coins from the JSON file if the coin is not found in the featured list
- After switching on, show spinner when checking decimals and switch on
