### ISSUE TITLE
Debug Section in Settings: Network logs of client.

### ISSUE THREAD

**Issue by uberkerim** [horizontalsystems/unstoppable-wallet-ios#285]
- [ ] network logs
- [ ] any other logs that may be relevant for debugging
- [ ] display current network tx fee rates for each supported blockchain
- [ ] display current exchange rates for base_currency and supported crypto

more details to be provided

**Comment by esengulov** [comment]
@uberkerim @ealymbaev if it's for debugging purposes then set it only on dev build

**Comment by uberkerim** [comment]
This ticket should be changed to cover all the cases. Main purpose is to make sure which ipfs location client tried to access, was it successful. I see this as network logs. This is applicable only for dev version of application.

**Comment by esengulov** [comment]
The issue is already implemented and no longer relevant
