### ISSUE TITLE
System dark/light mode bugs

### ISSUE THREAD

**Issue by mNizhurin** [horizontalsystems/unstoppable-wallet-ios#2873]
- [x] chart lines and text
- [x] gradient on read more cell
- [x] BottomGradientHolder
- [x] check splash screen, appears always dark on ea - phone

**Comment by TalgatNurdinov** [comment]
- [ ] Change the colors of items in Welcome Screens
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0-Unstoppable-Design-System?node-id=32337%3A299731

**Comment by mNizhurin** [comment]
![photo_2021-04-14 23 37 48](https://user-images.githubusercontent.com/1726387/114754527-7d60d100-9d7a-11eb-93a0-0108f5c7201f.jpeg)
![photo_2021-04-14 23 37 45](https://user-images.githubusercontent.com/1726387/114754537-7fc32b00-9d7a-11eb-8a6d-8fd647d86e2c.jpeg)
