### ISSUE TITLE
Solana and SPL tokens, Serum DEX support

### ISSUE THREAD

**Issue by Zhuvikin** [horizontalsystems/unstoppable-wallet-ios#2951]
This proposes to add Solana network as well as SPL-tokens support. The network has the fastest transaction confirmation which is very useful for the practical applications.
Please consider https://spl.solana.com/token as the docs 

Also, the swaps between SPL tokens is possible via Serum DEX API https://projectserum.com

**Comment by Dadybayo** [comment]
Soon, we plan to add missing blockchains to Unstoppable such as Avalanche/Polkadot/Monero/Algorand/Solana 

At this stage, we have already integrated DEXes like Uniswap/Pancakeswap which cover all possible needs of our users

For this reason, the task of supporting the Solana blockchain and integrating Serum DEX is not a priority for us at the moment
