### ISSUE TITLE
Add a warning that jailbroken devices are unsafe, but leave the ultimate decision up to the user.

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-ios#2968]
Alert text

>> The Unstoppable app works only on non-rooted (not jailbroken) phones.

>>Please note when you use a rooted device the app can no longer guarantee the safety of your cryptocurrency from malicious software.

button text "I UNDERSTAND"

**Comment by TalgatNurdinov** [comment]
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0-Unstoppable-Design-System?node-id=34071%3A311745
