### ISSUE TITLE
Add new icons

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-ios#2977]
- [x] YIELDWATCH
- [x] Binance-Peg Cardano Token (ADA)
- [x] Alice (ALICE)
- [x] AlpaToken (ALPA)
- [x] AlpacaToken (ALPACA)
- [x] MTLX-ERC20 (anyMTLX)
- [x] AS Rome (ASR)
- [x] Atletico de Madrid (ATM)
- [x] Binance-Peg Cosmos Token (ATOM)
- [x] AllianceBlock Token (bALBT)
- [x] bDollar (BDO)
- [x] Beflect.finance (BFI)
- [x] Multiplier(bMXX)
- [x] Bondly Token (BONDLY)
- [x] OPEN Governance Token (bOPEN)

- [x] Ellipsis (EPS)
- [x] Pancake Bunny (BUNNY)
- [x] Value DeFi (VALUE)
- [x] Alpaca Finance (ALPACA)
- [x] Fei Protocol (FEI)
- [x] Alien Worlds (TLM)
- [x]  Verasity (VRA)
- [x] GamerCoin (GHX)
- [x] Zipmex Tken (ZMT)
- [x] Olympus (OHM)
- [x] Travala.com (AVA)
- [x]  Uquid Coin (UQC)
- [x] Velas (VLX)
- [x] Newscrypto Coin (NWC)
- [x] Liquity USD (LUSD)
- [x] Conflux (CFX)
- [x] Anchor Protocol (ANC)
- [x] HBTC Captain Token (HBC)
- [x] THORChain (ERC20) (RUNE)
- [x] Kin (KIN)
- [x] PAID Network (PAID)
- [x] TitanSwap (TITAN)
- [x] Everipedia (IQ)
- [x] Pancake Bunny (BUNNY)
- [x] Tribe (TRIBE)
- [x] Pundi X (PUNDIX)

- [x] BUX Token (BUX)
- [x] CanYaCoin (CAN)
- [x] Contentos (COS)
- [x] dego.finance (DEGO)
- [x] DeXe (DEXE)
- [x] DefiDollar DAO (DFD)
- [x] DODO bird (DODO)
- [x] Binance-Peg Polkadot Token (DOT)
- [x] Dusk Network (DUSK)
- [x] Elrond (EGLD)
- [x] Binance-Peg EOS Token (EOS)
- [x] The Force Token (FOR)
- [x] fry.world (FRIES)
- [x] Frontier Token (FRONT)
- [ ] Fuel Token (FUEL)
- [x] FC Barcelona Fan Token (BAR)
- [x] Paris Saint-Germain Fan Token (PSG)
- [x] Juventus Fan Token (JUV)
- [x] Galatasaray Fan Token (GAL)
- [x] AC Milan Fan Token (ACM)
- [x] Atletico Madrid Fan Token (ATM)
- [x] OG Fan Token (OG)
- [x] AS Roma Fan Token (ASR)
- [x] Sint-Truidense Voetbalvereniging Fan Token (STV)
- [x] Team Heretics Fan Token (TH)
- [ ] Trabzonspor Fan Token (TRA)
- [ ] Apollon Limassol Fan Token (APL)
- [ ] Natus Vincere Fan Token (NAVI)

**Comment by kansalt** [comment]
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0-Unstoppable-Design-System?node-id=33673%3A302877
