### ISSUE TITLE
Market: Add new categories 

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-ios#2992]
- [x] Fan Tokens
>> Digital fan tokens, typically specific to a team or club .

- [x] Investment Tools
>> Token-powered analytics and investment instruments.

**Comment by TalgatNurdinov** [comment]
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0-Unstoppable-Design-System?node-id=27291%3A226045

change "Prediction" category icon to new icon, for "Investment Tools" use market icon which used by Prediction
