### ISSUE TITLE
Even though I chose EUR as base currency, the prices on the "Markets" page are displayed in USD

### ISSUE THREAD

**Issue by roman009** [horizontalsystems/unstoppable-wallet-ios#2995]
I have chosen EUR as base currency in the settings, but the prices on the Markets page are displayed in USD. When I go to the market data page for BTC, for example, I see the price in EUR, which is correct.

![unnamed (1)](https://user-images.githubusercontent.com/14812536/116821255-73f8a680-ab79-11eb-94a2-e0f4ea0a6fb7.png)
![unnamed (2)](https://user-images.githubusercontent.com/14812536/116821259-778c2d80-ab79-11eb-862e-7fe5de90865f.png)

**Comment by esengulov** [comment]
Hi,

Thanks for heads up! This has been already fixed in the upcoming version and should hopefully be available in App Store  end of next week.
