### ISSUE TITLE
Zec sends failed, error messages, zec disappeared, then reappeared

### ISSUE THREAD

**Issue by zusanalleghra** [horizontalsystems/unstoppable-wallet-ios#3017]
I accidentally tried to send 3 ZEC when I meant to send $3 to pay for a coffee. That transaction failed due to insufficient funds. But then all transactions after that failed for mysterious reasons like "timeout".

Then I opened my wallet and it showed 0 ZEC.

Later I opened my wallet again and my ZEC was back. I was able to send normally.

I have screen-recordings of this entire sequence of events that I can share with you privately.

**Comment by Dianaaiym** [comment]
> I accidentally tried to send 3 ZEC when I meant to send $3 to pay for a coffee. That transaction failed due to insufficient funds. But then all transactions after that failed for mysterious reasons like "timeout".
> 
> Then I opened my wallet and it showed 0 ZEC.
> 
> Later I opened my wallet again and my ZEC was back. I was able to send normally.
> 
> I have screen-recordings of this entire sequence of events that I can share with you privately.

Hi,

Please send a video screen by email (email address: support.unstoppable@protonmail.com)

**Comment by Dianaaiym** [comment]
We could not reproduce and there is no answer from you.
Reopen the ticket if necessary
