### ISSUE TITLE
transactions tab refactoring (UI and architecture)

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#3040]

**Comment by TalgatNurdinov** [comment]
- [ ] Rename titles of cells to Sent/Receive/Swapped/Approved for completed transactions (also use in the status cell instead completed)

- [ ] Fix the wrong background color

- [ ] Add coin code for unlimited value in the approvals cells  (unlimited CRV)

-[ ] Remove “-“ from sent transactions 

- [ ] Add blockchain names for contract calls
