### ISSUE TITLE
show user a custom alert when s/he tries to send entire ETH/BNB balance while having active ERC20/BEP20 tokens

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#3083]
@Dianaaiym alert text
`Consider leaving some COIN_SYMBOL on balance to be able to pay for future transactions.`

**Comment by TalgatNurdinov** [comment]
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0-Unstoppable-Design-System?node-id=34948%3A325579

https://user-images.githubusercontent.com/42367908/118600815-52332c80-b7d3-11eb-9468-e40c8afd42e4.mov

**Comment by TalgatNurdinov** [comment]
https://www.figma.com/proto/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?page-id=9319%3A178&node-id=47072%3A438747&viewport=341%2C48%2C0.47&scaling=scale-down&starting-point-node-id=47072%3A438747&show-proto-sidebar=1
