### ISSUE TITLE
update recommended coins list

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#3121]
https://github.com/horizontalsystems/unstoppable-wallet-android/issues/3781

**Comment by Dadybayo** [comment]
- Uniswap 
- Chainlink 
- Polygon 
- Aave 
- Maker 
- PancakeSwap 
- Compound 
- Sushi
- Synthetix 
- yearn.finance
- Curve
- 1inch 
- Balancer

**Comment by esengulov** [comment]
@Dianaaiym The list above from @Dadybayo  is incomplete,  the final list is in the Notion document.
