### ISSUE TITLE
Cannot Send XRP to Exchange or Other Wallet

### ISSUE THREAD

**Issue by Cyclic** [horizontalsystems/unstoppable-wallet-ios#3132]
Attempting to send XRP to another wallet address outside of Unstoppable Wallet, and receive the error "invalidAddress". Tried both Kraken, which requires a tag, and Trust Wallet, which does not require a tag since it's a cold wallet; however, both addresses complain that they're invalid.

**Comment by Dianaaiym** [comment]
> Attempting to send XRP to another wallet address outside of Unstoppable Wallet, and receive the error "invalidAddress". Tried both Kraken, which requires a tag, and Trust Wallet, which does not require a tag since it's a cold wallet; however, both addresses complain that they're invalid.

Hi,
Unstoppable supports XRP (BEP2 - Binance) You don't need a tag to send XRP(BEP2)
