### ISSUE TITLE
Walletconnect deep link broken on iOS

### ISSUE THREAD

**Issue by robgraeber** [horizontalsystems/unstoppable-wallet-ios#3157]
1. Go to aave on your iPhone
2. Try to connect your wallet via walletconnect and click on the unstoppable icon in the modal.
3. See that it redirects you to a link like: https://unstoppable.money//wc?uri=wc%3Adec2c1f2-dd00-4553-a617-7faead4da4c9%4...
4. However this link doesn't open the unstoppable app like other wallets in the modal.

This modal is used on a lot of walletconnect enabled sites. Currently it is not possible to use walletconnect and browse defi on the same phone. Ideal fix is fixing the deep link and adding a button to load a qr screenshot for the walletconnect qr scanner like other wallets.

**Comment by mNizhurin** [comment]
This feature is currently in development in version 0.22. Issue: #2829

Wallet connect has no testnet - alike version so Unstoppable wallet appeared there before actual release..
