### ISSUE TITLE
Coin info >> funds invested: add fund data for protocols

### ISSUE THREAD

**Issue by Dadybayo** [horizontalsystems/unstoppable-wallet-ios#3213]
[Summary-Unstoppable Wallet Feauture (1).csv](https://github.com/horizontalsystems/unstoppable-wallet-ios/files/6789831/Summary-Unstoppable.Wallet.Feauture.1.csv)

[Final Version-Grid view.csv](https://github.com/horizontalsystems/unstoppable-wallet-ios/files/6789891/Final.Version-Grid.view.csv)

**Comment by esengulov** [comment]
Issue Merged Into https://github.com/horizontalsystems/unstoppable-wallet-ios/issues/3221
