### ISSUE TITLE
Buttons and tabs refactoring

### ISSUE THREAD

**Issue by TalgatNurdinov** [horizontalsystems/unstoppable-wallet-ios#3217]
- [x] Primary Buttons redesign 

- [x] Secondary Buttons redesign 

- [x] Remove tertiary buttons style (replace with secondary)

https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0-Unstoppable-Design-System?node-id=36051%3A331670

- [x] Tabs redesign 
Coins / Guides - Top
Market / Keys - Top - Fitted

- [x] Period Tabs

https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0-Unstoppable-Design-System?node-id=36051%3A337974

- [x] Sorting headers redesign

https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0-Unstoppable-Design-System?node-id=24840%3A119387

- [x] sorting buttons on balance tab. change ' 24h Price(%) ' to ' Price Change'

- [x] change 'Add coin' button/text to icon

**Comment by kansalt** [comment]
Update the button icons on the balance card
- [ ] Replace the "receive" button icon with "icon / 24 / arrow / medium-3 / down-left"
- [ ] Update the "icon / 24 / arrow / swap-2" on "swap" button

**Comment by kansalt** [comment]
- [ ] Change the text color of primary buttons to "Claude"
- [ ] Add new toggle buttons
