### ISSUE TITLE
Coin Page Enhancements v3

### ISSUE THREAD

**Issue by Dadybayo** [horizontalsystems/unstoppable-wallet-ios#3221]
https://github.com/horizontalsystems/unstoppable-wallet-ios/issues/3221#issuecomment-886648858

**Comment by Dadybayo** [comment]
Task transferred to sprint 23, all data ready and ready for implementation on UI side

**Comment by esengulov** [comment]
**Investor Data**
 
- [ ] add Treasuries section
- [ ] add Reports section
- [ ] light UI refactoring for Funds section. 
[Summary-Unstoppable Wallet Feauture (1).csv](https://github.com/horizontalsystems/unstoppable-wallet-ios/files/6789831/Summary-Unstoppable.Wallet.Feauture.1.csv) / [Final Version-Grid view.csv](https://github.com/horizontalsystems/unstoppable-wallet-ios/files/6789891/Final.Version-Grid.view.csv)

- [ ] integrate PRO feature capability. The items which are listed below AND market as PRO should only be available to users holding Unstoppable Wallet token. 

**Token Liquidity**

- [ ] add 'DEX Volume'  (+ historical chart) PRO
- [ ] add 'DEX Volume rank' (+ rank list) PRO
- [ ] add 'DEX Liquidity' (+ historical chart) PRO
- [ ] add 'DEX Liquidity rank' (+ rank list) PRO

**Token Distribution**

- [ ] add 'Active Adresses' (+ historical chart) PRO
- [ ] add 'Active Adresses rank'  (+ rank list) PRO
- [ ] add 'Transaction Count' (+ historical chart) PRO
- [ ] add 'Transaction Volume' (+ rank list) PRO
