### ISSUE TITLE
Error while running the project for the first time

### ISSUE THREAD

**Issue by pushp1010** [horizontalsystems/unstoppable-wallet-ios#3319]
Is anyone facing such error? Even after doing pod install 👍 

<img width="361" alt="Screenshot 2021-08-13 at 11 39 16 AM" src="https://user-images.githubusercontent.com/52121407/129312774-f09d4023-c325-4137-91fc-dd1f21609502.png">

**Comment by mNizhurin** [comment]
Make sure you complete all steps from read me. Especially step 3.

**Comment by pushp1010** [comment]
Yes I did

**Comment by Embtra** [comment]
<img width="1210" src="https://user-images.githubusercontent.com/90335791/132535054-ecdec9cb-1f30-4530-939d-fb76cef3ef24.png">

It is impossible for me to compile the project for the first time. What are the requirements?

**Comment by mNizhurin** [comment]
Which version of your xcode? Please use at least 12.5.1 version.
