### ISSUE TITLE
walletconnect: change the connection steps and add new states

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#3342]

**Comment by kansalt** [comment]
- [ ] action for the first connect of “walletconnect” > after pushing "walletconnect" section on "settings" tab > open "walletconnect page" > than open "scan page” 
https://user-images.githubusercontent.com/58926737/130436640-283ebe1f-7fcd-4e8f-84d2-f59a6ec49788.mov

- [ ] after scan and connecting > close the "scan page” > open "confirm screen" of connection
- [ ] after opening the "confirm screen" of connection > the "confirm screen" of connection should not be closed on swipe until the user connects the session or canceled it
- [ ] same action for the "confirm screen" of transactions (approve,swap) > should not be closed on swipe until the user choose "swap", "approve" or rejected it

- [ ] add texts for the "hud" > "disconnecting" and "done"
https://user-images.githubusercontent.com/58926737/130438522-143d5440-0056-48e4-979d-4d258fd3e011.mov

- [ ] add "reconnect" button for the "offline" state of "connection page"
https://user-images.githubusercontent.com/58926737/130438565-84a9fcc3-b1db-4b3f-8130-8425c1b570e5.mov

- [ ] add "no internet" state for the "connection page"
Uploading Screen Recording 2021-08-23 at 5.06.00 PM.mov…

**Comment by kansalt** [comment]
- [ ] Add the "Done" hud after clicking the "Disconnect" button.
- [ ] Add the text for the "offline" state. 
`Failed to establish connection. Try reconnecting again.`
