### ISSUE TITLE
Not able to generate build (missing required architecture arm64 )

### ISSUE THREAD

**Issue by harinderstealth** [horizontalsystems/unstoppable-wallet-ios#3370]
app is running perfectly fine on simulator but when i try to run on real iPhone it gives error  in ZcashLightClientKit missing required architecture arm64. please check link attached for better understanding.

using xcode 12.4
macbook intel

[https://imgur.com/a/xHTaAva](url)

**Comment by ant013** [comment]
Hi! i give same error every time when change platform from simulator to device and back. It's because zCash library can be builds only for one of them. You can try manually delete app folder "Pods" from project and run "pod install" or try deintegrate pods and install again.

**Comment by harinderstealth** [comment]
@ant013 Thanks buddy it works now
