### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by trustwalletvn** [horizontalsystems/unstoppable-wallet-ios#3389]
Cannot build 
1. `git clone git@github.com:horizontalsystems/unstoppable-wallet-ios.git`
2. `cp UnstoppableWallet/UnstoppableWallet/Configuration/Development.template.xcconfig  UnstoppableWallet/UnstoppableWallet/Configuration/Development.xcconfig`
3. `cp UnstoppableWallet/UnstoppableWallet/Configuration/Production.template.xcconfig UnstoppableWallet/UnstoppableWallet/Configuration/Production.xcconfig`
4. `curl https://sh.rustup.rs -sSf | sh`
5. chose 1 Proceed with installation (default)
5. close Terminal
6. `cargo install cargo-lipo`
7. `rustup target add aarch64-apple-ios x86_64-apple-ios`
8. `brew install sourcery`
9. `pod install`
10. Open in Xcode and run
Error below:

Showing Recent Messages
Unable to load contents of file list: '/Target Support Files/Pods-Unstoppable Dev/Pods-Unstoppable Dev-resources-Debug-input-files.xcfilelist'

**Comment by trustwalletvn** [comment]
Best answer is delete Unstoppable Dev target 💯  
Run OK

**Comment by uber9** [comment]
Closing this issue, since according to previous comment it seems resolved.
