### ISSUE TITLE
integrate EIP-1559

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-ios#3395]
- [x] apply new UI for fee setting
- [x] Research/Apply the tool to prevent overpayment of transaction fees as fallback/addition for the integration EIP-1559 https://decrypt.co/80930/ethereums-infura-releases-tool-prevent-overpayment-transaction-fees

**Comment by Dianaaiym** [comment]
https://twitter.com/lefterisjp/status/1443143599235944451?s=28

**Comment by Dianaaiym** [comment]
https://twitter.com/lefterisjp/status/1443143599235944451?s=28

**Comment by TalgatNurdinov** [comment]
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?node-id=47117%3A439714
