### ISSUE TITLE
Change the text color of the Primary yellow button to "Dark" for dark and light modes

### ISSUE THREAD

**Issue by kansalt** [horizontalsystems/unstoppable-wallet-ios#3659]

**Comment by kansalt** [comment]
- [ ] Apply the same change to the "secondary" yellow buttons

**Comment by TalgatNurdinov** [comment]
@mNizhurin please, complete this point
https://github.com/horizontalsystems/unstoppable-wallet-ios/issues/3659#issuecomment-978885323

**Comment by mNizhurin** [comment]
да вы че ахуели?

**Comment by mNizhurin** [comment]
сэкондари елоу баттонс есть только на табе для чартов, там и так черный текст на желтой кнопке, че еще надо??
