### ISSUE TITLE
Ethereum NFT Collections Page

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#3700]
- NFT Collections list page
- show total price for all assets
- make ability to switch price (Last Price and Floor Price)

**Comment by TalgatNurdinov** [comment]
Layouts:
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?node-id=45885%3A420321

Prototype:
https://www.figma.com/proto/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?page-id=22050%3A2377&node-id=45885%3A420321&viewport=241%2C48%2C0.29&scaling=scale-down&starting-point-node-id=45885%3A420321&show-proto-sidebar=1
