### ISSUE TITLE
Same contract on ERC20 and BEP20, can only add ERC20

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-ios#3724]
When I added a contract that is on both ERC20 and BEP20 with the same contract address, it take only the ERC20 address, impossible to get the BEP20.
0x6b23C89196DeB721e6Fd9726E6C76E4810a464bc

**Comment by esengulov** [comment]
@Dianaaiym are you sure the token has an ERC20 contract ? Both coin gecko and Unstoppable api shows only one contract instance and it's on BSC
