### ISSUE TITLE
Coin Page : Add PRO features

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#3725]
In this sprint we intent to expand the details tab of the coin page with premium analytics data. That data would only be available to users holding Unstoppable token.

- [x] Analytics section of the COIN Page should provide access to the following analytical data
-- Onchain DEX volume (UniswapV2,V3, Sushiswap, PancakeswapV1/V2) for the token (+ historical chart)
-- Onchain DEX liquidity (UniswapV2,V3, Sushiswap, PancakeswapV1/V2) for the token (+ historical chart)
-- Active Adresses for the token  (+ historical chart)
-- Onchain TX count for the token (+ historical chart)
-- Onchain TX volume for the token (+ historical chart)
-- Avg 30d revenue per day for the project represented by the token (@TalgatNurdinov this needs to be added to coin page)

- [ ] @tmedetbekov The PRO analytics should only be available to users holding Unstoppable Wallet token. Before the Unstoppable token is implemented enable this feature for holders of the following collections: BAYC, MAYC, CryptoPunk.

**Comment by TalgatNurdinov** [comment]
NFT page opens by clicking on the locked items in coin page, and you can also open the NFT (minting) page from the settings

COIN PAGE
https://www.figma.com/proto/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?page-id=9325%3A9106&node-id=40237%3A327459&viewport=341%2C48%2C0.14&scaling=scale-down&starting-point-node-id=40242%3A328550&show-proto-sidebar=1

SETTINGS
https://www.figma.com/proto/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?page-id=22050%3A2377&node-id=45492%3A420011&viewport=241%2C48%2C0.29&scaling=scale-down&starting-point-node-id=45492%3A420011
