### ISSUE TITLE
Unable to build project

### ISSUE THREAD

**Issue by kcochibili** [horizontalsystems/unstoppable-wallet-ios#3776]
Hello, first off, you guys have an amazing project. 
I am trying to build the project locally, and I have followed all the instructions, but everything related to pods are giving errors. 
I have tried `pod install` but it doesn't fix the errors.

Below is a screenshot  of the errors after cloning the project.

<img width="1440" alt="Screen Shot 2022-01-04 at 4 03 45 PM" src="https://user-images.githubusercontent.com/6098606/148132868-6af9a14c-0777-47b6-a035-7458edcdcdac.png">
<img width="1440" alt="Screen Shot 2022-01-04 at 4 25 07 PM" src="https://user-images.githubusercontent.com/6098606/148132869-3cd9218e-ab75-4cd9-ae99-e73637f64e92.png">
<img width="1440" alt="Screen Shot 2022-01-04 at 4 25 17 PM" src="https://user-images.githubusercontent.com/6098606/148132870-aea27810-a341-455b-9c31-42d4b2157e29.png">
<img width="1440" alt="Screen Shot 2022-01-04 at 5 27 58 PM" src="https://user-images.githubusercontent.com/6098606/148132873-c68f00f4-ad88-4bd3-8ec7-2bbf6aeca599.png">

Please can you provide further instructions on how to resolve or get past these errors?

**Comment by esengulov** [comment]
Did you try Googling. The error seems related to your local config

**Comment by kcochibili** [comment]
I initially didn't google it because the errors seemed specific to this project. 
After googling the error, it turned out I needed to `deintegrate` my pods first, before opening xcode or attempting to build this project.

This is a crucial step and should be included in the Readme of this project.

For future people who will encounter these errors, follow these steps below after the steps outlined on the readme of this project (before building the app)

1. cd into the projects folder from the terminal; that is the inner folder containing the ``UnstoppableWallet.xcodeproj`` file.
while there, 
2. Run: ``pod deintegrate`` this will clean up former pod configurations
3. then run ``pod install``

**Comment by Pragmatic2021** [comment]
I think everybody is kinda pissed at me right now. Possibly forever IDK. The easiest thing to do would be to delete it. Don't worry about.

**Comment by Pragmatic2021** [comment]
> I initially didn't google it because the errors seemed specific to this project. 
> 
> After googling the error, it turned out I needed to `deintegrate` my pods first, before opening xcode or attempting to build this project.
> 
> 
> 
> This is a crucial step and should be included in the Readme of this project.
> 
> 
> 
> For future people who will encounter these errors, follow these steps below after the steps outlined on the readme of this project (before building the app)
> 
> 
> 
> 1. cd into the projects folder from the terminal; that is the inner folder containing the ``UnstoppableWallet.xcodeproj`` file.
> 
> while there, 
> 
> 2. Run: ``pod deintegrate`` this will clean up former pod configurations
> 
> 3. then run ``pod install``
> 
> 
> 
>

**Comment by Pragmatic2021** [comment]
Seriously, I'm going to do as you say. It's 2150, CDT Eastern US. By morning I expect they'll take this one down as well. Move on to a viable project. This one's DOA.

**Comment by samisbakedham** [comment]
> Seriously, I'm going to do as you say. It's 2150, CDT Eastern US. By morning I expect they'll take this one down as well. Move on to a viable project. This one's DOA.

What?

**Comment by ClaraBara22** [comment]
It’s complicated. I couldn’t find any content in the nice repo you built.
They (yes you) , get a little pissy with me because they find my work
unacceptable or something like that.
Thanks
Catherine

**Comment by ClaraBara22** [comment]
I meant NOT you. I don’t know where this came from but I entered it in
error. I’m still kinda annoyed.

**Comment by Pragmatic2021** [comment]
All the above notwithstanding, if you’d like to have another go at it and see it it actually yields any coin. I’m not encouraged I don’t know why I continue to return here for repositories. They never pay because by the time everybody gets it ready, late because they had to fix it. GH is not the only company of that nature.

**Comment by Pragmatic2021** [comment]
I’ve never had a fraction of a coin in Wallet Services and Unstoppable Wallet is definitely not user friendly. Just so you know.
