### ISSUE TITLE
Where to get API keys from?

### ISSUE THREAD

**Issue by kcochibili** [horizontalsystems/unstoppable-wallet-ios#3777]
There seems to be no instructions or guide on where to get corresponding api keys for the project. that is the API keys I can put in the  `Production.template.xcconfig` in the configuration folder is. 

currently, the values are all empty:
```
infura_project_id =
infura_project_secret =
etherscan_api_key =
bscscan_api_key =
cryptocompare_com_api_key =
defiyield_api_key =
twitter_bearer_token =
market_api_url = https:/$()/api.blocksdecoded.com
hs_provider_api_key =
```

can you list the resources of where I can get my own keys?

**Comment by esengulov** [comment]
All these api keys can be on rained from corresponding services i.e. infura.io

**Comment by kcochibili** [comment]
Thank you for the hint, I was able to acquire all api keys except `hs_provider_api_key` 
There is no pointer on where or how to get it. I also checked on blocksdecoded.com but I did not see anything related to getting an api key there. 

Can you point me to where to get my api key for the `hs_provider`?

for all the other ones, I am going to post their sources on here for anyone who may need the info in the future. I still think this should be in the ReadMe of this project.

`infura_project_id`: infura.io create an Ethereum project
`infura_project_secret`: infura.io
`etherscan_api_key`: etherscan.io
`bscscan_api_key` = bscscan.com
`cryptocompare_com_api_key`: cryptocompare.com
`defiyield_api_key`: gist.github.com/kcochibili/5cbdff4337f6e94578e7a53c71f09f42
`twitter_bearer_token`: developer.twitter.com/en/docs/authentication/oauth-2-0/bearer-tokens
`market_api_url` = https:/$()/api.blocksdecoded.com
`hs_provider_api_key`: I dont know this

**Comment by itravelerorg** [comment]
kcochibili did you get hs_provider_api_key? If yes, so where from?

**Comment by kcochibili** [comment]
@itravelerorg  I wasn't able to get it, but from my research, it looks like it is provided by HorizontalSystems (the owner of this repository)

For now, the app seems to work fine without it (further tests still needed).
On the android side, one of the project maintainers said the key is no longer needed in the latest version. I don't know if this update applies to IOS as well, take a look here: https://github.com/horizontalsystems/unstoppable-wallet-android/issues/3862#issuecomment-877147453
