### ISSUE TITLE
EVM networks: Add Polygon 

### ISSUE THREAD

**Issue by Dadybayo** [horizontalsystems/unstoppable-wallet-ios#3811]
Polygon
-- has its own token (MATIC)

**Comment by esengulov** [comment]
@ealymbaev above we made a list of L2 EVM chains. Please review and see which one can be easily integrated into the app.

**Comment by zxstorm** [comment]
Any chance of implementing ability to add **custom** EVM-compatible chains?

**Comment by esengulov** [comment]
> Any chance of implementing ability to add **custom** EVM-compatible chains?

yes, it will be part of that feature

**Comment by Dadybayo** [comment]
1inch supports 4 EVM chains:
- Polygon 
- Arbitrum 
- Optimism
- Gnosis Chain 

Uniswap supports 3 EVM chains:
- Polygon 
- Optimism 
- Arbitrum

@ealymbaev
