### ISSUE TITLE
Add THORChain swap provider

### ISSUE THREAD

**Issue by Zhuvikin** [horizontalsystems/unstoppable-wallet-ios#3828]
As a user I would like to use THORChain swap provider in addition to existing ones like Uniswap and 1Inch on Swap page.
This will bring new functionality of cross-chain swaps between native coins like BTC, ETH, LTC and etc...

**Comment by esengulov** [comment]
@Zhuvikin thanks, we will look into it. 

Upon testing the service I could not swap ETH to BTC. Tried two times:
>> 0.1 ETH to BTC
>> 0.2 ETH to BTC

Do you use the service?
