### ISSUE TITLE
Why is bitcoin not swappable with other coins?

### ISSUE THREAD

**Issue by kcochibili** [horizontalsystems/unstoppable-wallet-ios#3838]
In the Balance module, when Bitcoin is expanded, the exchange button is hidden by default.
Also, in the swap module Bitcoin is not among the coins you can swap. 

Is there an explanation for this?

**Comment by Dianaaiym** [comment]
> In the Balance module, when Bitcoin is expanded, the exchange button is hidden by default. Also, in the swap module Bitcoin is not among the coins you can swap.
> 
> Is there an explanation for this?

Unstoppable Wallet only supports swap for erc20 and bep20 tokens
