### ISSUE TITLE
Refactor auto-enable coin behavior

### ISSUE THREAD

**Issue by ealymbaev** [horizontalsystems/unstoppable-wallet-ios#3978]
`Bulk Auto-Enable` feature should work only for restored EVM blockchains. It should use HS backend for fetching list of tokens with balances. Backend will provide the current block number and rates for tokens as well. The following tokens should be enabled in this case:

- token has a rate and its fiat value is more than $1

For Watch wallets the filter above should not be applied, in other words, all tokens should be enabled.

`Auto-Enable on Tx` feature should work for all EVM blockchains when a new transaction is detected.

- new transactions should be parsed and all interacted tokens should be fetched from parsing
- if the fetched token is not enabled yet - it should be enabled
- this feature should also work for Watch wallets

P.S. Thus HS provider will be only used on wallet restore or watch wallet, and should not be used later on sync (only new transactions will trigger enabling new coins)

**Comment by Tomcherry117687** [comment]
merged
