### ISSUE TITLE
[Question] How does Unstoppable sync with the BTC blockchain?

### ISSUE THREAD

**Issue by vetko** [horizontalsystems/unstoppable-wallet-ios#3984]
I tried to search for this information, but unfortunately I wasn't able to find anything, neither on Google nor in the [faq](https://unstoppable.money/faq) nor between the [github issues](https://github.com/horizontalsystems/unstoppable-wallet-ios/issues).

Can you please give a bit more details on how the sync with blockchains works (in particular with the BTC blockchain)?
For example, are you using any BIPs to achieve that (e.g. BIP 37, BIP 157 / 158, or something else)? Or is it some kind of full-sync?

Thank you.

**Comment by esen** [comment]
Hey @vetko ,

We use bitcoin BIP37 (SPV) client implementation in [bitcoin-kit-ios](https://github.com/horizontalsystems/bitcoin-kit-ios) repository. Bitcoin network can be synced fully from bitcoin peers as described in SPV protocol, OR you can chose to use our optimized synchronization. Optimized synchronization uses checkpoints of the blockchain which are updated in each app release and our API to retrieve transactions before those checkpoints. After the chain is synced once, it continues to sync only from the peers via SPV protocol. Using full SPV or optimized sync is chosen by the user in the wallet settings.

**Comment by vetko** [comment]
Hi @esen, thanks for the answer!

I see that there has been some investigation in 2019 regarding introducing BIP 157/158 (neutrino) to Unstoppable (https://github.com/horizontalsystems/unstoppable-wallet-android/issues/716). Is there any chance that this gets back on the radar again?
(Not asking from the point of view of introducing the Lightning Network to Unstoppable, but rather changing BIP 37 to BIP 158).

**Comment by esen** [comment]
We don't have any plans on that in a near future. We definitely will switch to neutrino or some kind of other solutions which may be more optimized for the client. More and more nodes are disabling Bloom Filters on their side, so this is a matter of time. But currently, we don't have any concrete plans on it.
