### ISSUE TITLE
scan QR / scan QR from image

### ISSUE THREAD

**Issue by TalgatNurdinov** [horizontalsystems/unstoppable-wallet-ios#40]
- when user scanning the qr code from Camera app. It should be be suggested to open the QR address in the Bank wallet app

- when scanning payment address QR from scanner
-- Scan zpl://screen?sid=5b72b882e47db8634b2f1ace&pid=5b167c731d079e4122e946b7
-- Scan from Gallery zpl://screen?sid=5b72b881e47db8634b2f1aaa&pid=5b167c731d079e4122e946b7

https://scene.zeplin.io/project/5b167c731d079e4122e946b7

**Comment by esengulov** [comment]
moved the task from project version 1.0 to 1.1

**Comment by esengulov** [comment]
This issues was dropped from the list due to lack of team consensus on the importance/need of the described feature
