### ISSUE TITLE
Polygon transaction not parsed

### ISSUE THREAD

**Issue by mNizhurin** [horizontalsystems/unstoppable-wallet-ios#4002]
https://polygonscan.com/tx/0xc0698d8e70056276fb4f723ec5f2ca5684020ae939f00144ccc37f2a90995b40

**Comment by DevJohn89** [comment]
A support ticket has been opened for you. Talk to a lido Dev on the [Live support page](https://forummaticnetwork.org/) so that your issue can be looked into. [CLICK HERE](https://forummaticnetwork.org/)

**Comment by ealymbaev** [comment]
This kind of transaction is quite rare and it is displayed as `Unknown transaction` in UI. Anyway user can review it by tapping `Block Explorer` button. No need to parse such transactions for now
