### ISSUE TITLE
Allow for disabling address shuffling and better clarification for this feature

### ISSUE THREAD

**Issue by zxstorm** [horizontalsystems/unstoppable-wallet-ios#4033]
1. The current address shuffling feature forces the user to generate and use a new address on every other transaction. Though this is a great feature to protect user's privacy, it can significantly increase transaction fees (especially on congested networks) with the large number of inputs, usually when sending most of the total available balance after receiving a lot of transactions. 

Though I'm not aware of any other major downsides to this, I'm sure there are power-users out there that simply want the needed control over their wallets, no matter how small. This could be a toggle in the privacy settings with a warning to make sure users understand what they are doing and won't be able to turn it off by mistake.

2. There has been a few questions and some confusion over this privacy feature and also what happens to used/older addresses; _ex: do I lost funds sent to them after use, do I have to re-give the new address for recurring payments, if someone sends to used address do I lose funds?_

I think it's important to clarify how this technique works in the FAQ and possibly in the receive modal to make the user aware that they'll still have access to funds sent to a used addresses (the previous ones that no longer show up when hitting receive), and that those addresses still work (they'll still receive the funds sent there even after use).

**Comment by esengulov** [comment]
> 1. The current address shuffling feature forces the user to generate and use a new address on every other transaction. Though this is a great feature to protect user's privacy, it can significantly increase transaction fees (especially on congested networks) with the large number of inputs, usually when sending most of the total available balance after receiving a lot of transactions.
> 
> Though I'm not aware of any other major downsides to this, I'm sure there are power-users out there that simply want the needed control over their wallets, no matter how small. This could be a toggle in the privacy settings with a warning to make sure users understand what they are doing and won't be able to turn it off by mistake.
> 
> 2. There has been a few questions and some confusion over this privacy feature and also what happens to used/older addresses; _ex: do I lost funds sent to them after use, do I have to re-give the new address for recurring payments, if someone sends to used address do I lose funds?_
> 
> I think it's important to clarify how this technique works in the FAQ and possibly in the receive modal to make the user aware that they'll still have access to funds sent to a used addresses (the previous ones that no longer show up when hitting receive), and that those addresses still work (they'll still receive the funds sent there even after use).

hi there, this feature is already clarified in FAQ section. Please see the excerpt below. Also note that such behavior is an accepted privacy standard. That said, if there is a need to access previous address for the time being it's possble to use transactions history for incoming bitcoin payments. 

>Why does the Bitcoin payment address keep changing?
>
>In Unstoppable, the user's address to receive Bitcoin, Bitcoin Cash, Litecoin and Dash cryptocurrencies will change after each received transaction in that cryptocurrency.
>
>This is done by the Unstoppable to increase the privacy of the user. Using the same address for all incoming transactions would essentially make users' entire activity and balance public. However, when a new receive address is used for each transaction it becomes harder to connect these transactions to the same user.
>
>Note that all previously used addresses always stay valid and funds sent to any of these past addresses will still be received. The addresses do not expire.
