### ISSUE TITLE
Treasuries: list scrolling bug

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-ios#4042]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/22589457/162724531-05f102b3-6f39-4526-b832-88331a9976f6.gif)

**Comment by ealymbaev** [comment]
This issue is not related to app UI, but to iOS issues. I could not find any known fixes for this issue. And assuming this issue is minor - closing it until next iOS release.
