### ISSUE TITLE
Add private key restore for Bitcoin

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-ios#4104]

**Comment by Tomcherry117687** [comment]
merge-these-changes

**Comment by esengulov** [comment]
After discussion with the devs we dedcided to postpone this issue to 0.28 or later as it carriest substantial UI review and fixes. Primarily, adding this feature would require restricting certain coins from appearing on coin manager based on the wallet type etc

**Comment by Dianaaiym** [comment]
https://github.com/horizontalsystems/unstoppable-wallet-ios/issues/4503
