### ISSUE TITLE
[Bug] Watch address and crash.

### ISSUE THREAD

**Issue by qoli** [horizontalsystems/unstoppable-wallet-ios#4157]
Address: 0x6782472a11987e6f4A8aFB10dEF25B498Cb622db

**Step:**
1. add a new watch address;
2. this address (0x6782472a11987e6f4A8aFB10dEF25B498Cb622db);
3. crash;
4. reopen all and crash again.

**Comment by Dianaaiym** [comment]
> Address: 0x6782472a11987e6f4A8aFB10dEF25B498Cb622db
> 
> **Step:**
> 
> 1. add a new watch address;
> 2. this address (0x6782472a11987e6f4A8aFB10dEF25B498Cb622db);
> 3. crash;
> 4. reopen all and crash again.
Hi,

Thank you for the feedback!
It was fixed in 0.25, the update will be available next week.
