### ISSUE TITLE
Invalid parsing of data for `Markets` tab in `CoinPage`

### ISSUE THREAD

**Issue by ealymbaev** [horizontalsystems/unstoppable-wallet-ios#4182]
Tickers are parsed incorrectly. Currently `symbol`s are compares in order to identify base/target coin for ticker.

But in some cases (e.g. `GST-BSC`) symbol in ticker and in coin itself are different. Coin uid should be used for comparing instead of symbol.

**Comment by Mike117687** [comment]
merge-these-changes
