### ISSUE TITLE
Position of the floating action buttons when the keyboard is active

### ISSUE THREAD

**Issue by TalgatNurdinov** [horizontalsystems/unstoppable-wallet-ios#4201]
Keyboard should push float active button upward

- [ ] Restore
- [x] Watch Address
- [x] Swap Settings

The button should be inactive if the necessary data are not filled in

? - Backup, Send

**Comment by ant013** [comment]
@TalgatNurdinov please test on different devices

**Comment by kansalt** [comment]
- [ ] Change the padding of the button from the keyboard to 16px
