### ISSUE TITLE
List of Tokens to Add to Categories

### ISSUE THREAD

**Issue by Dadybayo** [horizontalsystems/unstoppable-wallet-ios#4208]
Options
- [x]  Hxro (HXRO) 
- [x] Premia (PREMIA) 
- [x] AntiMatter (MATTER)

Infrastructure 
- [x] Gelato (GEL) 
- [x] Synapse (SYN) 
- [x] EDEN (EDEN) 
- [x] Marlin (POND) 
- [x] JUNO (JUNO)
- [x] Chain (XCN)

Index Funds 
- [x] Interest Compounding ETH Index (ICETH) 
- [x] Bankless BED Index (BED) 
- [x] Index Coop - ETH 2x Flexible Leverage Index (Polygon) (ETH2X-FLI-P) 
- [x] Bankless DeFi Innovation Index (GMI) 
- [x] Yearn Ecosystem Index (YETI)

Risk Management 
- [x] Uno Re (UNO) 
- [x] Tidal Finance (TIDAL) 
- [x] Unslashed Finance (USF)

Stablecoins 
- [x] Dola (DOLA) 
- [x] USDD (USDD) 
- [x] STASIS EURO (EURS) 
- [x] mStable USD (MUSD)

Exchange Tokens 
- [x] ApolloX (APX)

Scaling 
- [x] Optimism (OP)

Identity 
- [x] Dock (DOCK)

Storage 
- [x] Aleph.im (ALEPH)

Privacy 
- [x] Automata (ATA) 
- [x] Nym (NYM) 
- [x] MobileCoin (MOB)

NFT 
- [x] JPEG'd (JPEG) 
- [x] CEEK Smart VR (CEEK)

Oracles 
- [x] UMA (UMA) 
- [x] XYO Network (XYO) 
- [x] iExec RLC (RLC)

Gaming 
- [x] My DeFi Pet (DPET) 
- [x] Thetan Arena (THG) 
- [x] Step App (FITFI) 
- [x] Riot Racers (RIOT) 
- [x] Genopets (GENE) 
- [x] Green Satoshi Token on BSC (GST-BSC) 
- [x] Alien Worlds (TLM) 
- [x] Dawn Protocol (DAWN) 
- [x] Highstreet (HIGH)

Yield Aggregartors 
- [x] Stake DAO (SDT)

Lending 
- [x] Inverse Finance (INV) 
- [x] Goldfinch (GFI) 
- [x] Maple (MPL) 
- [x] BENQI (QI) 
- [x] Kava Lend (HARD)
- [x] Beta Finance (BETA) 
- [x] JPEG'd (JPEG) 
- [x] Notional Finance (NOTE) 
- [x] Solend (SLND) 

DEXes 
- [x] DeversiFi (DVF) 
- [x] ApolloX (APX) 
- [x] CoW Protocol (COW) 
- [x] Maiar DEX (MEX) 
- [x] Gnosis (GNO) 
- [x] Sun Token (SUN) 
- [x] Platypus Finance (PTP)

Blockchains 
- [x] Dogecoin (DOGE) 
- [x] Klaytn (KLAY)

Analytics
- [x] DappRadar (Radar)

**Comment by Mike117687** [comment]
merge-these-changes
