### ISSUE TITLE
Update Bitcoin api

### ISSUE THREAD

**Issue by Retropex** [horizontalsystems/unstoppable-wallet-ios#4229]
<img width="414" alt="image" src="https://user-images.githubusercontent.com/74937347/174080263-1988ebb4-ff0e-44ce-9795-9c99ddb10494.png">

**Comment by Dianaaiym** [comment]
> <img alt="image" width="414" src="https://user-images.githubusercontent.com/74937347/174080263-1988ebb4-ff0e-44ce-9795-9c99ddb10494.png">

Salut,

Les développeurs ont déjà mis à jour l'API pour le bitcoin, au moment où la mise à jour est testée du côté d'Apple, la mise à jour pour android est déjà sur le Play Market.

Mais vous pouvez toujours restaurer votre portefeuille bitcoin via Blockchain (Paramètres - Centre de sécurité - Bitcoin, changez la source de restauration en 'Depuis Blockchain').

Dès que la mise à jour sera en ligne, nous vous tiendrons au courant, merci !

HS

**Comment by Dianaaiym** [comment]
> <img alt="image" width="414" src="https://user-images.githubusercontent.com/74937347/174080263-1988ebb4-ff0e-44ce-9795-9c99ddb10494.png">

La mise à jour est disponible dans l'App Store
