### ISSUE TITLE
Changes on the "Restore", "Watch Address" screens

### ISSUE THREAD

**Issue by ealymbaev** [horizontalsystems/unstoppable-wallet-ios#4290]

**Comment by kansalt** [comment]
- [ ] Update the text
- [ ] Swap the "inputs" 

<img width="820" alt="Screen Shot 2022-07-18 at 2 30 25 PM" src="https://user-images.githubusercontent.com/58926737/179473273-88aa24a1-8060-4137-b1c4-9fc91c41e888.png">

https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?node-id=55530%3A281033
