### ISSUE TITLE
ui showing incorrect information/imposter tokens

### ISSUE THREAD

**Issue by InTheMorning** [horizontalsystems/unstoppable-wallet-ios#4326]
Searching for the 10set (Tenset) token via discovery yields only one result: a seemingly real Tenset token, complete with the market price and data for the real token.  However, the contract is for a scam token.

Is this intended behavior for the ui to show market price/data based solely on the token's name, rather than its actual contract?

![image](https://user-images.githubusercontent.com/4637290/181393337-8745d4ef-ef26-4e1b-a103-2f52a07ec70d.png)
![image](https://user-images.githubusercontent.com/4637290/181393360-6e854eea-a597-4ca3-8e47-bdcee1405c3d.png)

**Comment by Dianaaiym** [comment]
Hi,

Thank you for the feedback!

10set migrated to new contract 0x1AE369A6AB222aFF166325B7b87Eb9aF06C86E57.
0x1F64fdAD335ED784898EFFb5ce22D54d8f432523 is his old contract. We have updated our database, the changes will appear on your side within 24 hours.
