### ISSUE TITLE
OpenSea: Does not allow to sign the transaction

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-ios#4431]
Selling and buying are not possible on the OpenSea via UW. The approval passes correctly, and after signing the tx on the side of the wallet, an error appears on the OpenSea  "invalid order signature"

**Comment by valuxin** [comment]
Is there any chance you release new version with this bug fixed soon? Can't sign anything for so long neither at opensea or rarible...
