### ISSUE TITLE
2FA 

### ISSUE THREAD

**Issue by AIcyberark** [horizontalsystems/unstoppable-wallet-ios#4438]
Will unstoppable wallet support 2FA verification in the future?

**Comment by horsys** [comment]
> Will unstoppable wallet support 2FA verification in the future?

Depends. We definitely not going to offer 2FA tied to mobile no/email as that would require us to keep the records on our end which we don't do. That said, there can be some other ways to add additional secuirty check when user attempts to send funds i.e. asking user for an additional 6 digit code or something along those lines. Not in the near term roadmap though.
