### ISSUE TITLE
Add caret ^ support in BIP39 Passphrase, the only ASCII character missing in version 0.26 Android/iOS

### ISSUE THREAD

**Issue by VincentBounce** [horizontalsystems/unstoppable-wallet-ios#4480]
![IMG_8060](https://user-images.githubusercontent.com/64386272/191314683-6ea99f47-34c7-4b70-b576-94635eaec1a6.jpg)

**Comment by Dianaaiym** [comment]
> ![IMG_8060](https://user-images.githubusercontent.com/64386272/191314683-6ea99f47-34c7-4b70-b576-94635eaec1a6.jpg)

Hi,

Thank you for your feedback!

This is already fixed in sprint 0.27. The new version will be available soon)
