### ISSUE TITLE
Crash after add a watch address 0x4976fb03c32e5b8cfe2b6ccb31c09ba78ebaba41

### ISSUE THREAD

**Issue by qoli** [horizontalsystems/unstoppable-wallet-ios#4482]
I add a watch address: 0x4976fb03c32e5b8cfe2b6ccb31c09ba78ebaba41

I change to this address.

now, I open the app and crash after 2 ~ 3 secs.

**Comment by ealymbaev** [comment]
This address is not user address, but contract address. We had no intention to support watching contract addresses, but in version 0.27 this crash is already fixed in #4465
