### ISSUE TITLE
After restoring wallet with one bitcoin address from recovery phrase, cannot add more bitcoin addresses

### ISSUE THREAD

**Issue by meglio** [horizontalsystems/unstoppable-wallet-ios#4499]
Steps to reproduce:

1. Create a new wallet, write down the recovery phrase.
2. Go to Settings, Manage Wallet, Unlink
3. Recover the wallet with using the recovery phrase. Select only one bitcoin address (the default one).
4. See only one bitcoin entry in the Balance.
5. Go to the BTC Settings and turn on the other two addresses.
6. Go to the Balance.
7.1. Issue: there is still just one BTC in the list.
7.2 Expected: there are three BTC in the list (one per address type) - unlike when you create a new wallet and select all three bitcoin address types straight away, in which a case three BTC addresses are shown as expected.

**Comment by ant013** [comment]
Hi! Can't reproduce on version 0.27. As you can see. I created new wallet, turn on only one Bip, then go to "add token" -> "BTC settings" and turn on 2 other bips. It's working fine.

https://user-images.githubusercontent.com/13083244/194857791-8a8daa23-d137-43c1-9d17-c52d7ad2879e.mov

**Comment by meglio** [comment]
@ant013 ,

> Hi! Can't reproduce on version 0.27. As you can see. I created new wallet, turn on only one Bip, then go to "add token" -> "BTC settings" and turn on 2 other bips. It's working fine.

These steps are not what I described in the reproduction steps.

**Comment by ant013** [comment]
> 

This is step by step video.

https://user-images.githubusercontent.com/13083244/198960118-fed90225-438f-4bdc-bad4-c6392cb88488.mp4
