### ISSUE TITLE
Switching to next derived address 

### ISSUE THREAD

**Issue by Oxngon** [horizontalsystems/unstoppable-wallet-ios#4537]
I am not sure if it’s a feature or a bug: when copying receiving address, the wallet automatically switches to next derived address.

First time it happened, it was scary because I created new wallet, copied address, made incoming transaction and while I saw tx confirmation on blockchain but nothing showed up in the wallet -> when I noticed different address. I put two and two together, that the receiving address has been changed to the next derived address:

https://iancoleman.io/bip39/

This happens with every version of BTC (at least, didn’t check other networks) wallets. How to reproduce:

- create new wallet
- click receive, copy address
- send tx to the address
- go back to app, same wallet, click receive -> new address will show up without user input, old address is “lost”.

The only way to “fix” it is to restore the wallet again, where first address will show up again (incl the transaction after chain synced up).

I am assuming this is some privacy preserving feature to avoid using the same wallet address for all transactions but it makes the entire wallet almost unusable. I tried to search if there’s options to control it in settings to no avail. It can be detrimental, especially for new/inexperienced users.

**Comment by Dianaaiym** [comment]
> 

Hi,

Thank you for the feedback!
It isn't a bug, it's a feature. Once a public address (btc, bch, dash, ltc) receives an incoming payment, a new address will automatically be generated and displayed when you click on Receive.

**Comment by Oxngon** [comment]
How do you expect the assets that have been received in “old” derived address to be spent (without restoring wallet again)?

**Comment by Dianaaiym** [comment]
> How do you expect the assets that have been received in “old” derived address to be spent (without restoring wallet again)?

All addresses that have been generated for your account will remain associated with your account forever. They are safe to re-use to receive future payments,
