### ISSUE TITLE
When creating a wallet, indicate the recommended mnemonic (12 words)

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-ios#4555]
![2022-11-23 15 08 48](https://user-images.githubusercontent.com/22589457/203508119-fec4d03e-a5bc-4312-9883-438c4e9faa5d.jpg)

**Comment by esen** [comment]
https://github.com/horizontalsystems/unstoppable-wallet-ios/issues/4595

duplicate ?
