### ISSUE TITLE
Error building ZcashLightClientKit (CompactBlockProcessor)

### ISSUE THREAD

**Issue by Cod4h** [horizontalsystems/unstoppable-wallet-ios#4571]
Hello!

I'm trying to build the app from the source code (last release) and I'm getting these 4 errors when Xcode tries to build ZcashLightClientKit:

`/Library/Developer/Xcode/DerivedData/UnstoppableWallet-emtporhibqqfjtcabfreldqpxfkp/SourcePackages/checkouts/ZcashLightClientKit/Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift:1115:10: Actor-isolated instance method 'transactionEnhancementProgressUpdated' cannot be used to satisfy a protocol requirement`

`/Library/Developer/Xcode/DerivedData/UnstoppableWallet-emtporhibqqfjtcabfreldqpxfkp/SourcePackages/checkouts/ZcashLightClientKit/Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift:371:5: Designated initializer for 'CompactBlockProcessor' cannot delegate (with 'self.init'); did you mean this to be a convenience initializer?`

`/Library/Developer/Xcode/DerivedData/UnstoppableWallet-emtporhibqqfjtcabfreldqpxfkp/SourcePackages/checkouts/ZcashLightClientKit/Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift:392:12: Designated initializer for 'CompactBlockProcessor' cannot delegate (with 'self.init'); did you mean this to be a convenience initializer?`

`/Library/Developer/Xcode/DerivedData/UnstoppableWallet-emtporhibqqfjtcabfreldqpxfkp/SourcePackages/checkouts/ZcashLightClientKit/Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift:1133:55: Cannot infer return type for closure with multiple statements; add explicit type to disambiguate`

<img width="278" alt="Captura de Pantalla 2022-11-30 a la(s) 16 04 17" src="https://user-images.githubusercontent.com/87586393/204887562-2186a000-4f5e-43e5-963f-fdd6597f22f0.png">
<img width="684" alt="Captura de Pantalla 2022-11-30 a la(s) 16 04 25" src="https://user-images.githubusercontent.com/87586393/204887579-f599e212-9434-4688-b63c-3e4a35c7f35d.png">

**Comment by ant013** [comment]
Hello! Im sorry for delay. We make hotfix changes in code, because some Zcash repository branches was deleted. Can you please update source code and clean derived data. If errors will appear again, please write which Zcash brach version Xcode use in your project. Thanks
