### ISSUE TITLE
Private Key display issue for wallets imported by Private Key

### ISSUE THREAD

**Issue by VincentBounce** [horizontalsystems/unstoppable-wallet-ios#4618]
To reproduce the bug:

Use Unstoppable 0.28.3 iOS. Passcode defined. No FaceID/TouchID.
Have 2 imported wallets: 1 wallet imported with seed, 1 wallet imported with private key.

✅Settings > Manage Wallets > [24 words wallet (imported with seed)] > ⋮ > EVM Private Key > Passcode > Tap to show private key > [the private key is well displayed, no problem here].

❌Settings > Manage Wallets > [EVM Private Key wallet (imported with private key)] > ⋮ > EVM Private Key > Passcode > [nothing happens, the problem is here!]

Thank you to fix this.

**Comment by Dianaaiym** [comment]
> To reproduce the bug:
> 
> Use Unstoppable 0.28.3 iOS. Passcode defined. No FaceID/TouchID. Have 2 imported wallets: 1 wallet imported with seed, 1 wallet imported with private key.
> 
> ✅Settings > Manage Wallets > [24 words wallet (imported with seed)] > ⋮ > EVM Private Key > Passcode > Tap to show private key > [the private key is well displayed, no problem here].
> 
> ❌Settings > Manage Wallets > [EVM Private Key wallet (imported with private key)] > ⋮ > EVM Private Key > Passcode > [nothing happens, the problem is here!]
> 
> Thank you to fix this.

Hi,

It was already fixed  https://github.com/horizontalsystems/unstoppable-wallet-ios/issues/4540
New version 0.29 is coming soon!)
