### ISSUE TITLE
Feature request: I want to encrypt my wallet private keys using smartcard (Yubikit)

### ISSUE THREAD

**Issue by kristoffer-paulsson** [horizontalsystems/unstoppable-wallet-ios#4644]
I want Yubiko Yubikey PIV encryption of assets stored in my wallet locally to be decryted by external token!

The best whing is to use the following libs:
https://github.com/Yubico/yubikit-ios
https://github.com/Yubico/yubikit-android

The alternative is to use an obsolete wallet called Evercoin, they disappeared.

https://www.yubico.com/se/works-with-yubikey/catalog/evercoin/

**Comment by esengulov** [comment]
we would like to postpone this for the time being as it's not entirely clear whether there are significant benefits of it for wider user base. that said, we will reconsider if there are more similar requests

**Comment by kristoffer-paulsson** [comment]
I believe the yubikey wallets would be impossible to steal from the app if phone is lost or hacked, just sayin, I'm an targeted individual. Thanks for the app, learned great things from the Academy.

**Comment by esengulov** [comment]
> I believe the yubikey wallets would be impossible to steal from the app if phone is lost or hacked, just sayin, I'm an targeted individual. Thanks for the app, learned great things from the Academy.

we are considering to. implement it in the near future. Hopefully in release 0.34

**Comment by Dianaaiym** [comment]
Closing as not planned for now, focusing on other priorities. May revisit in the future.
