### ISSUE TITLE
Refactor onboarding: UI for create/restore/watch screens

### ISSUE THREAD

**Issue by horsys** [horizontalsystems/unstoppable-wallet-ios#4653]
- [x] Refactor CREATE screen (rename title of page to “New Wallet”)
- add the input field for ‘Wallet Name’ and move advanced creation settings to the page ADVANCED (on Advanced page also add input for wallet name)

- [x] Refactor RESTORE screen (rename title of page to “Import Wallet”)
- default restore should provide input field for ‘Wallet Name’ and 'Recovery Phrase' and should not require user to adjust any settings
- move advanced creation settings to the page ADVANCED.

- [x] Rename the title of “Watch Wallet” page to “Watch Wallet”

- [x] Remove Avalanche from coins list that are activated by default. Keep BTC, ETH, BNB, USDT(ERC20), BUSD(BEP20)

Layouts:
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?node-id=66246%3A312104&t=CkTU4JjOcVb1rS6B-4

**Comment by esengulov** [comment]
- [ ] refactor CREATE screen
- default creation should not require user to adjust any settings
- move advanced creation settings to a separate ADVANCED SETTINGS section that with radio button.
- [ ] refactor RESTORE screen
- default restore should only provide input field for 'Recovery Phrase' and should not require user to adjust any settings
- move advanced restore settings to a separate ADVANCED SETTINGS section that with radio button.
- [ ] refactor WATCH screen
-- allow user select a chain after selecting 'WATCH' option.
-- after user selects chain open the screen with the input field.
- [ ] remove Avalanche from coins list that are activated by default. Leave only BTC, ETH, BNB

**Comment by Dianaaiym** [comment]
- [ ] remove additional text
![IMAGE 2023-01-20 17:17:07](https://user-images.githubusercontent.com/22589457/213682980-678eac8d-2c22-47f5-8362-564a131fa352.jpg)

- [ ] add padding
![2023-01-20 17 17 31](https://user-images.githubusercontent.com/22589457/213683141-ee1d9768-62ab-4565-831c-a9a4e3dfe756.jpg)

**Comment by Dianaaiym** [comment]
- [ ] Remove last checkbox
![2023-01-25 15 37 20](https://user-images.githubusercontent.com/22589457/214529098-291c73a9-cece-45c3-9669-27a49383b9e6.jpg)
