### ISSUE TITLE
Allow sending Ethereum transaction with lower gas fee than current block's fee + custom nonce

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#4662]
https://github.com/horizontalsystems/unstoppable-wallet-android/issues/5673

- [ ] Transaction Fee 
>The maximum fee a user is expected to pay for the given transaction. Typically, the actual fee for the transaction is going to be lower. 

- [ ] Gas Limit 
>Ethereum transactions vary in complexity and are measured in so-called gas units. This setting shows the expected maximum amount of gas units to spend on a given transaction. The gas limit is estimated and set automatically for each transaction. 

- [ ] Base Fee 
>The price of a single gas unit at any given time is known as the current base fee (or gas price). It changes in real time with network conditions and is not controlled by any single entity. 

- [ ] Max Fee Rate (Gwei)
>The max. The fee rate is the maximum price for a gas unit a user is willing to pay when sending the given transaction. 

- [ ] Max Miner Tip (Gwei)
>The miner tip is essentially a small bribe to blockchain nodes (aka miners) in order to incentivize the faster processing of the given transaction.

- [ ] TX nonce
>The nonce is the number of transactions sent from a given address. Each time user sends a transaction, the nonce value increases by 1. Changing the nonce might be needed when a user tries to invalidate the currently pending transaction (that might have been sent in error etc) by sending another transaction with the same nonce but a higher fee. If there are two pending transactions with the same nonce only one will be accepted.

**Comment by TalgatNurdinov** [comment]
Nonce input in the fee settings page

https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?node-id=66299%3A311215&t=e7OZ7jSvLKM31ndy-11

**Comment by Dianaaiym** [comment]
![2023-03-01 18 01 41](https://user-images.githubusercontent.com/22589457/222133892-21c9ce65-a9d4-4dfb-a3d9-be2c6fab0717.jpg)
