### ISSUE TITLE
Settings to declutter UI by disabling some features

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#4664]
https://github.com/horizontalsystems/unstoppable-wallet-android/issues/5721

**Comment by TalgatNurdinov** [comment]
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?node-id=66047%3A299080&t=to1MfHXvhnuwnTAA-11
