### ISSUE TITLE
Update app info on ethereum.org. Send a pull request

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-ios#4765]

**Comment by Dadybayo** [comment]
[https://github.com/ethereum/ethereum-org-website/issues/9451](url)

**Comment by Dadybayo** [comment]
https://github.com/ethereum/ethereum-org-website/issues/9451

**Comment by Dianaaiym** [comment]
A pull request has been submitted to [ethereum.org](http://ethereum.org/).
 https://github.com/ethereum/ethereum-org-website/pull/10133
