### ISSUE TITLE
Coin Page : Expand Data on Analytics Tab

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#4791]
Implement new analytics page that has following data

- [x] CEX volume
- [x] DEX volume
- [x] DEX liquidity
-- chart in this component should have minimum duration of 1 month
- [x] Active addresses
- [x] Transaction count
- [x] Holders
- [x] Project TVL
- [x] Project revenue
- [x] all rank cells should allow transition to the list view
- [x] implement new UI look
-- the look for locked state (regular user)
-- the look for unlocked state (premium user)
- [x] use the info texts supplied in the comment below

**Comment by TalgatNurdinov** [comment]
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?node-id=67915%3A324409&t=tfZItjUJpd4Kh2eb-11
