### ISSUE TITLE
Update Categories 

### ISSUE THREAD

**Issue by Dadybayo** [horizontalsystems/unstoppable-wallet-ios#4802]
### Blockchains

**To adding** 
- [x] Aptos 
- [x] Toncoin - TON

### DEXes 

**To removing** 
- [x] Ellipsis - EPS 
- [x] Solidly - Solid 
- [x] Gnosis - GNO

**To adding** 
- [x] VVS Finance - VVS 
- [x] PolkaBridge - PBR
- [x] OpenOcean - OOE
- [x] ApeX - APEX 
- [x] Gains Network - GNS 
- [x] Mute - Mute 
- [x] HashFlow - HFT

### Lending 

**To changing**
- [x] Hifi Finance - HIFI [https://www.coingecko.com/en/coins/hifi-finance](url)

**To adding**
- [x] Euler - EUL
- [x] Alchemix - ALCX

### Yield Aggregators 

**To removing**
- [x] Rari Governance - RGT

### Gaming 

**To removing**
- [x] Riot Racers - Riot 

**To adding**
- [x] dotmoovs - MOOV
- [x] Vulcan Forged - PYR
- [x] Radio Caca - RACA
- [x] League of Kingdoms - LOKA
- [x] COCOS BCX - COCOS
- [x] Bluzelle - BLZ
- [x] TridentDAO - PSI
- [x] Bora - BORA
- [x] Wemix - WEMIX

### Oracles 

**To adding**
- [x] Oraichain - ORAI

### NFT 

**To adding**
- [x] Blur - BLUR
- [x] APENFT - NFT 
- [x] SuperVerse - SUPER
- [x] sudoswap - SUDO

### Privacy 

**To remove**
- [x] Ocean Protocol - OCEAN

### Wallets 

**To removing**
- [x] Cronos - CRO 
- [x] Gnosis - GNO 
- [x] Bread - BRD

**To adding**
- [x] Aurox - URUS
- [x] Klever - KLV 

### Scaling 

**To changing** 
- [x] Elrond [https://www.coingecko.com/en/coins/multiversx](url)

**To removing** 
- [x] Hermez Network - HEZ 

### Yield Tokens 

**To adding** 
- [x] sETH2 - SETH2
- [x] sETH - SETH
- [x] Convex CRV - CVXCRV
- [x] Convex FXS - CVXFXS
- [x] Lido Staked Ether - STETH

### Exchange Tokens 

**To adding** 
- [x] Bitget Token - BGB
- [x] Tokenize Xchange - TKX
- [x] AscendEx - ASD
- [x] BitMEX - BMEX
- [x] Bitrue Coin - BTR

### StableCoins 

**To adding** 
- [x] Coin98 Dollar - CUSD
- [x] Origin Dollar - OUSD
- [x] Reserve - RSV
- [x] agEUR - AGEUR
- [x] Celo Euro - CEUR
- [x] BOB - BOB
- [x] TOR - TOR
- [x] Vesta Stable - VST
- [x] YUSD Stablecoin - YUSD

### Risk Management 

**To removing** 
- [x] Armor - ARMOR 

**To changing** 
- [x] Certik - CTK [https://www.coingecko.com/en/coins/shentu](url)

### Index Funds 

**To removing**
- [x] PieDAO Balanced Crypto Pie - BCP
- [x] Bankless DeFi Innovation Index - GMI
- [x] Yearn Ecosystem Token Index 

**To adding**
- [x] Colony Avalanche Index - CAI
- [x] Total Crypto Market Cap - TCAP

### Prediction 

**To adding**
- [x] SX Network - SX

### Fundraising

**To removing** 
- [x] Cardcaster - CARDS 

### Infrastructure 

**To adding**
- [x] Hapi - HAPI 
- [x] Ocean Protocol - OCEAN 
- [x] Phala Network - PHA
- [x] Hacken - HAI

- [x] **Reserve Currency** **- DELETE THE FULL CATEGORY** 

### Options 

**To adding** 
- [x] Buffer Token - BFR

### Zero-Knowledge - NEW CATEGORY

**To adding**
- [x] ZKSpace - ZKS
- [x] Hermez Network - HEZ
- [x] Mina Protocol - MINA
- [x] Zcash - ZEC
- [x] Aleph Zero - AZERO
- [x] Horizen - ZEN
- [x] DUSK Network - DUSK
- [x] Loopring - LRC
- [x] Mute - MUTE
- [x] Railgun - RAIL
- [x] PIVX - PIVX

### AI - NEW CATEGORY 

**To adding**
- [x] SingularityNET - AGIX
- [x] Fetch.ai - FET
- [x] Artificial Liquid Intelligence - ALI
- [x] Numeraire - NMR
- [x] Oraichain - ORAI
- [x] SingularityDAO - SDAO
- [x] Altered State Machine - ASTO
- [x] Vaiot - VAI
- [x] GNY - GNY
- [x] DeepBrain Chain - DBC
- [x] Hera Finance - HERA
- [x] Botto - BOTTO
- [x] Matrix AI Network - MAN
- [x] dotmoovs - MOOV

**Comment by Dadybayo** [comment]
Also need to add 2 illustrations for new categories and descriptions to them

**Comment by TalgatNurdinov** [comment]
Images
https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?node-id=68297%3A342288&t=tfZItjUJpd4Kh2eb-11
