### ISSUE TITLE
add more data to pro analytics

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#4814]
- [x] add ratings to coin page
- [x] add Project Fees

**Comment by TalgatNurdinov** [comment]
Current state of design
<iframe style="border: 1px solid rgba(0, 0, 0, 0.1);" width="800" height="450" src="https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Fproto%2FM9MoqHabdQCdu2a9pIEo5N%2Fv.-2.0--Unstoppable-Design-System%3Fpage-id%3D30760%253A216718%26node-id%3D70745-458770%26viewport%3D-13224%252C-622%252C0.25%26scaling%3Dscale-down%26starting-point-node-id%3D70745%253A458770%26show-proto-sidebar%3D1" allowfullscreen></iframe>
