### ISSUE TITLE
App support TRX

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-ios#4895]

**Comment by Dianaaiym** [comment]
> Hi, Great app, i using it to track my wallets and one thing witch i would love to see is a tron integration. Maybe do you know approximately dates when it will be integrated? Thanks a lot))))

Hi,

Thank you for using Unstoppable as your crypto wallet! 

We estimate that the update will be ready in 2-3 weeks.

**Comment by sergeymild** [comment]
Thanks, i am looking forward for this feature)
