### ISSUE TITLE
Error when sending bitcoin 

### ISSUE THREAD

**Issue by bgmonitor1** [horizontalsystems/unstoppable-wallet-ios#4922]
I get an error when I try to send btc from my unstoppable wallet. 
It reads something like this “noPreviousOutputScript”
And doesn’t allow me to send. I’m using the latest version on AppStore

**Comment by tallman373** [comment]
me too , same error ...im using latest IOS version as well .

**Comment by tallman373** [comment]
> I get an error when I try to send btc from my unstoppable wallet. It reads something like this “noPreviousOutputScript” And doesn’t allow me to send. I’m using the latest version on AppStore

me too  , anyone else experiencing this , I emailed support ...waiting for response

**Comment by Dianaaiym** [comment]
> I get an error when I try to send btc from my unstoppable wallet. It reads something like this “noPreviousOutputScript” And doesn’t allow me to send. I’m using the latest version on AppStore

Hi,

Please restore your wallet again without deleting the existing one. Please refer to the attached screenshots.


![1](https://user-images.githubusercontent.com/22589457/235320731-9120f98c-ab28-47fa-aef8-c6b419f1bac6.jpg)
![2](https://user-images.githubusercontent.com/22589457/235320732-3ccb8797-4dba-4eda-8b9c-bad1b6cf9cb1.jpg)
![3](https://user-images.githubusercontent.com/22589457/235320735-e290e4d5-e82a-49a5-8beb-78ce45937ec6.jpg)

**Comment by tallman373** [comment]
thanks!On Apr 29, 2023, at 2:26 PM, imadia ***@***.***> wrote:﻿

I get an error when I try to send btc from my unstoppable wallet. It reads something like this “noPreviousOutputScript” And doesn’t allow me to send. I’m using the latest version on AppStore

Hi,
Please restore your wallet again without deleting the existing one. Please refer to the attached screenshots.
