### ISSUE TITLE
All sending transactions fails.

### ISSUE THREAD

**Issue by bgmonitor1** [horizontalsystems/unstoppable-wallet-ios#4924]
Hi,
I have tried to send to different types of addresses to no avail. All sending transactions failing, both on ios and android. My wallet is based on 24 words mnemonic and I’m using the latest versions. Is anyone else experiencing this?

**Comment by Dianaaiym** [comment]
Please restore your wallet again without deleting the existing one.

**Comment by bgmonitor1** [comment]
I deleted the old one already but I have my 24 word mnemonic seed.

Can restore with this?

What could be the cause of this? All transactions failing

**Comment by Dianaaiym** [comment]
Hotfix is available on App Store
https://apps.apple.com/us/app/unstoppable-crypto-wallet/id1447619907
