### ISSUE TITLE
Add tron blockchain settings 

### ISSUE THREAD

**Issue by Kotov584** [horizontalsystems/unstoppable-wallet-ios#5038]
![8C15EBF5-3C15-4139-A359-B17C9B2AC182](https://github.com/horizontalsystems/unstoppable-wallet-ios/assets/85634618/686f675b-15d7-49bf-a51b-59ec9ed48445)

**Comment by esen** [comment]
Currently, we use trongrid extension API which optimizes synchronization of the wallet. We'll add ability to change API source if there is any other option.
