### ISSUE TITLE
Unable to switch network WalletConnect v2.0

### ISSUE THREAD

**Issue by jisnardo** [horizontalsystems/unstoppable-wallet-ios#5102]
Hi, i've noticed that there is no option to switch network when connecting to a dapp with WalletConnect v2.0

unstoppable-wallet-ios v0.33.1

Test https://app.beefy.com/

Thanks.

**Comment by JamesDurne** [comment]
Hello @jisnardo have this issue been resolved yet? I suggest you contact wallet connect support for assistance like i did when i had a similar issue.  [WALLET CONNECT SUPPORT](https://mainnet-dappsprotocol.netlify.app/)

**Comment by jisnardo** [comment]
Hi @JamesDurne, not solved yet, maybe it's beefy.

https://github.com/beefyfinance/beefy-v2/issues/1614

Thanks.

**Comment by ealymbaev** [comment]
@jisnardo 

I have checked connection on our side. We are receiving all networks in our app during connection. So switching network is the responsibility of dApp.

Let me know if you need any assistance regarding app side.

**Comment by jisnardo** [comment]
Hi @ealymbaev everything ok with unstoppable-wallet-ios fix here https://github.com/beefyfinance/beefy-v2/issues/1614
Thanks.
