### ISSUE TITLE
Adding new value to fees after a BTC transaction has been sent (during its flight)

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-ios#5125]
I sent BTC today but unfortunately I only noticed after how low the commission fees were.

I'd like to add new value to the fees, but it's impossible for me to do that after the transaction is sent.

Might you solve this problem in the future?

**Comment by esengulov** [comment]
> I sent BTC today but unfortunately I only noticed after how low the commission fees were.
> 
> I'd like to add new value to the fees, but it's impossible for me to do that after the transaction is sent.
> 
> Might you solve this problem in the future?

hi, we do plan to add cancel/resend feature in the future but not in the immediate term. Meanwhile, please note that transaction recommendation engine was update in the latest release (0.34) which should prevent users from setting the transaction which is considered too low by the network.
