### ISSUE TITLE
Security center improvements: duress pin

### ISSUE THREAD

**Issue by kansalt** [horizontalsystems/unstoppable-wallet-ios#5210]
- [x] Change the default state of "Security Center”. Display all attributes regardless of the passcode enablement status.

- [x] Update the method for activating the passcode.

- [x] Add the action to set a passcode when enabling Face ID and Duress Mode > "if the password is not set”.

- [x] Move "Balance Auto Hide" from the "Appearance" section to the "Security Center" section and provide a description.

Implement a new function called "Duress Mode”.

- [x] Include a description of the function, wallet selection, passcode setting with the ability to edit and delete in the "Duress Mode" setup action. 

- [x] Duress Mode is activated only on screens with a Passcode during app unlock (at launch and app switching).

- [x] Face ID feature should unlock Duress Mode > "if Duress Mode is active".

- [x] Disabling the main passcode also deletes all Duress Mode settings.

Layouts:

https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?type=design&node-id=77119-196356&mode=design&t=b7kmtfc7Ko0327Bc-4

**Comment by Dianaaiym** [comment]
After creating the duress passcode, the "created" hud should be displayed at the top.

<img width="175" alt="Screenshot 2023-10-03 at 14 43 17" src="https://github.com/horizontalsystems/unstoppable-wallet-ios/assets/22589457/a2274be9-f78a-4364-83d2-9c048ecf0898">
