### ISSUE TITLE
Bitcoin Sync

### ISSUE THREAD

**Issue by Block321** [horizontalsystems/unstoppable-wallet-ios#5297]
How to increase sync speed of bitcoin like trust wallet?

**Comment by Block321** [comment]
any update?

**Comment by esen** [comment]
The work on this is in progress.

**Comment by Block321** [comment]
Thanks for updating
Let us know when its done

**Comment by esengulov** [comment]
> Thanks for updating
> Let us know when its done

expect improved sync in the coming update v 0.37 that's due next week

**Comment by Block321** [comment]
any update?

**Comment by esengulov** [comment]
> any update?

replying a bit late here) We have improved sync as much as we could without compromising on privacy. It's much faster now though though still not as fast as Trust Wallet. TW is fast because it knowns all user addresses and tracks their balances.
