### ISSUE TITLE
"Receive" page improvements

### ISSUE THREAD

**Issue by Dianaaiym** [horizontalsystems/unstoppable-wallet-ios#5381]
![2023-11-07 15 56 42](https://github.com/horizontalsystems/unstoppable-wallet-ios/assets/22589457/884e6945-14cd-4534-9cde-aa769e8b609a)
- [ ] Remove of Alert Text
- [ ] Implement a one-click copy-to-clipboard functionality for the address.

**Comment by TalgatNurdinov** [comment]
New design with set amount 

https://www.figma.com/file/M9MoqHabdQCdu2a9pIEo5N/v.-2.0--Unstoppable-Design-System?type=design&node-id=79973-206323&mode=design&t=OPWX9zSTb1hXCWEm-11
