### ISSUE TITLE
The swap (DEX) functionality is unavailable

### ISSUE THREAD

**Issue by windicted** [horizontalsystems/unstoppable-wallet-ios#5480]
There is no swap button at least for a wallet with ERC20 tokens. Unstoppable Wallet version: 0.36.2. iOS version: 16.7.2.

**Comment by Dianaaiym** [comment]
> There is no swap button at least for a wallet with ERC20 tokens. Unstoppable Wallet version: 0.36.2. iOS version: 16.7.2.

Due to Apple's restrictions, the swap feature has been removed, but you can download a version with swap from [TestFlight](https://testflight.apple.com/join/JaKdKPY5)
