### ISSUE TITLE
Wallet Connect: Switch network impossible

### ISSUE THREAD

**Issue by mario8O** [horizontalsystems/unstoppable-wallet-ios#5510]
Network cannot be switched or chosen upfront.
Example: revoke.cash cannot be used with Arbitrum network because of this missing feature.

**Comment by Dianaaiym** [comment]
> Network cannot be switched or chosen upfront. Example: revoke.cash cannot be used with Arbitrum network because of this missing feature.

Couldn't reproduce it, what version of the app?
