### ISSUE TITLE
Restoring Unstoppable Wallet from iMazing local backup

### ISSUE THREAD

**Issue by s0rl0v** [horizontalsystems/unstoppable-wallet-ios#5825]
Hello team!

Thank you for the great app, using it for two years already and it becomes better with every iteration.

Recently I lost my phone and all the data with it, all I had - iMazing backup which I do weekly. However I did not test the recovery process and it turned out that Unstoppable Wallet has no wallets after restore.

This is the backed up data:

<img width="754" alt="Screenshot 2024-05-17 at 9 39 00 PM" src="https://github.com/horizontalsystems/unstoppable-wallet-ios/assets/6148911/2d8f00ed-05e6-4a77-9c95-408be7fcecd0">

<img width="760" alt="Screenshot 2024-05-17 at 9 39 11 PM" src="https://github.com/horizontalsystems/unstoppable-wallet-ios/assets/6148911/0cb9b99c-fa4a-4c40-9c68-9ffa2ace99d4">

I still remember all the wallet app protection codes, apple id passwd, the device passcode etc, the problem is in missing data after recovery process.

Could you advise where the wallet stores wallets private keys? Is it possible to restore wallets or they are lost forever?

P.S. I did trust iMazing devs too much and did not use any inbiult backup features of the wallet, well, it was not very wise of me to do...

**Comment by ealymbaev** [comment]
Hi @s0rl0v,

All our sensitive data (including wallet mnemonic words, private keys, etc.) is stored in iOS Keychain. Moreover we store our data in keychain with `this device only` setting, thus making it unable to access it from another device.

Anyway our app would not allow you to receive funds without having a proper backup of your created wallet (manual or file/iCloud backup).
