### ISSUE TITLE
BTC can't sync

### ISSUE THREAD

**Issue by yellowroulette** [horizontalsystems/unstoppable-wallet-ios#5938]
Unstoppable wallet 0.39
ios 15.8.2

BTC always showing "Searching transactions..."
Tried to change Blockchains setting to Hybrid and restarting app. Changing to Bitcoin Blockchain didn't help too. Tried VPN and Wifi.
Other blockchains synced well and fast.

Edit: ERC20 doesn't sync too. I've tried both sources (Blocksdecoded and Llamanodes)

Edit 2: After a few hours, all other blockchains stopped syncing

**Comment by Dianaaiym** [comment]
> Unstoppable wallet 0.39 ios 15.8.2
> 
> BTC always showing "Searching transactions..." Tried to change Blockchains setting to Hybrid and restarting app. Changing to Bitcoin Blockchain didn't help too. Tried VPN and Wifi. Other blockchains synced well and fast.
> 
> Edit: ERC20 doesn't sync too. I've tried both sources (Blocksdecoded and Llamanodes)
> 
> Edit 2: After a few hours, all other blockchains stopped syncing

Hi,

Yesterday, some parts of the wallet, primarily related to blockchain and market data synchronization, experienced downtime. We identified and resolved the issue. In the next release, we will include an update with revised logic to prevent similar problems in the future.
