### ISSUE TITLE
Add unit/UI tests in the project

### ISSUE THREAD

**Issue by ankushkushwaha** [horizontalsystems/unstoppable-wallet-ios#5958]
I see that there are no test cases added in the project. Are we working on tests?

**Comment by SamWilsn** [comment]
We're actually looking this as part of Wallet Test Framework ([docs](https://wallet-test-framework.github.io/framework/), [repo](https://github.com/wallet-test-framework/framework), [blog](https://wtf.allwallet.dev/)). We've received a grant to add support for testing mobile wallets, and we've chosen Unstoppable as our first candidate.

**Comment by ankushkushwaha** [comment]
Okay, Good to know. Lets move forward.
