### ISSUE TITLE
Check out 

### ISSUE THREAD

**Issue by Stephyere** [horizontalsystems/unstoppable-wallet-ios#5995]
0xe4afc23ba374c02ab461fe155c20865ccdfbb625e4e9b4d347afd69f634b7ca0

**Comment by Dianaaiym** [comment]
> 0xe4afc23ba374c02ab461fe155c20865ccdfbb625e4e9b4d347afd69f634b7ca0

Please contact our official support (support.unstoppable@protonmail.com) if you need assistance with your transaction.
