### ISSUE TITLE
New logo/icon proposal

### ISSUE THREAD

**Issue by mansya** [horizontalsystems/unstoppable-wallet-ios#632]
Good day sir. I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before I begin my design. Hoping for your positive feedback. Thanks

**Comment by TalgatNurdinov** [comment]
Hi, Of course you can! Send your works to this repository
https://github.com/horizontalsystems/HS-Design
We will consider your offer
