### ISSUE TITLE
Transaction >> Verify : blcokexplorer.com seems to be always down

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#673]
It's down both for BTC and BCH.

Investigate why it's down (can ask @nk-the-crazy ) and if no quick fix disable it for both chains.

**Comment by esengulov** [comment]
Duplicate of # https://github.com/horizontalsystems/unstoppable-wallet-ios/issues/667

**Comment by mNizhurin** [comment]
duplicate #667
