### ISSUE TITLE
Balance tab sorting 

### ISSUE THREAD

**Issue by TalgatNurdinov** [horizontalsystems/unstoppable-wallet-ios#674]
Sort by 
- Value
- A-Z
- Manual

*if rate not available sort by value should be disabled (grey50)

<img width="770" alt="Screen Shot 2019-06-19 at 5 08 09 PM" src="https://user-images.githubusercontent.com/42367908/59760765-e7aaa680-92b4-11e9-9202-9b45afe2db1c.png">

https://zpl.io/2jM7g5r

Sort by menu
https://zpl.io/VYp161d

**Comment by esengulov** [comment]
please include mockups that have ONLY sorting by price/value/custom. no other elements should be included

**Comment by TalgatNurdinov** [comment]
- [ ] More clicking area for down/up button
- [ ] Rename
       Value to Balance
       Manual to Default
