### ISSUE TITLE
List of EOS-based tokens the wallet should support

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#694]
Check the coin list below and see if there are any issues in providing wallet support for the following EOS based tokens. It's an initial list of the EOS based tokens the wallet going to support.

You may get the contract address for each token here, https://bloks.io/tokens. Click on the token name and on the token page click on the iOS username

EOS (EOS) 
Newdex (NDX)
Everipedia (IQ)
EOSDT (EOSDT)
Native Utility Token (NUT)
Prospectors Gold (PGL)
MEET.ONE  (MEETONE)
Paytomat (PTI)

**Comment by nk-the-crazy** [comment]
Tokens supported by CryptoCompare:
1. EOS
2. IQ
3. PGL
4. MEETONE

**Comment by esengulov** [comment]
added token names

- EOS (EOS) 
- Newdex (NDX)
- Everipedia (IQ)
- EOSDT (EOSDT)
- Native Utility Token (NUT)
- Prospectors Gold (PGL)
- MEET.ONE  (MEETONE)
- Paytomat (PTI)

**Comment by esengulov** [comment]
The issue is already implemented and no longer relevant
