### ISSUE TITLE
Introduce Protocol for External Libraries

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#696]
Not so long ago, there was an attack on one of the wallets in the market. You may read about this here, https://blog.npmjs.org/post/185397814280/plot-to-steal-cryptocurrency-foiled-by-the-npm

With that in mind let's review all third party libraries used in the wallet as well as wallet kits and introduce a protocol about pulling 3rd party library updates moving forward.

**Comment by ealymbaev** [comment]
After reviewing all external libraries (pod) there is only one library that is required to be implemented on our own: `KeychainAccess`. It is used for storing and reading data from iOS keychain and therefore it has access to secure data.
The issue is already created for this case: #1080

**Comment by esengulov** [comment]
> After reviewing all external libraries (pod) there is only one library that is required to be implemented on our own: `KeychainAccess`. It is used for storing and reading data from iOS keychain and therefore it has access to secure data.
> The issue is already created for this case: #1080

noted!
