### ISSUE TITLE
how to add new erc20 token?

### ISSUE THREAD

**Issue by samfrm** [horizontalsystems/unstoppable-wallet-ios#698]
How to add support for new ERC20 tokens or our created token?
Is it possible to add a new token by contract address? Is there any document for that?

**Comment by Dianaaiym** [comment]
> How to add support for new ERC20 tokens or our created token?
> Is it possible to add a new token by contract address? Is there any document for that?

Thank you very much for your interest concerning our Wallet. 
If you're looking add ERC20 token into a Unstoppable Wallet, here is the repository for that https://github.com/horizontalsystems/Supported-ERC20-Tokens

**Comment by esengulov** [comment]
> How to add support for new ERC20 tokens or our created token?
> Is it possible to add a new token by contract address? Is there any document for that?

hey Sam, 

If you know your way around you may try commit to the repo directly. The repository has a file which lists all supported ERC20 tokens. 

You may also send it over here by replying to this thread. Note that we are not guarantee the inclusion. We are mostly adding tokens that are ties to the project which is available on the main net and/or has a fairly active team on Github.

**Comment by samfrm** [comment]
Hi @esengulov 
That's great, thank you for your guide .
