### ISSUE TITLE
Merge Restore and ManageKeys modules

### ISSUE THREAD

**Issue by ealymbaev** [horizontalsystems/unstoppable-wallet-ios#710]

**Comment by TalgatNurdinov** [comment]
<img width="1184" alt="Screen Shot 2019-07-09 at 5 28 06 PM" src="https://user-images.githubusercontent.com/42367908/60884546-eeeb2180-a26e-11e9-9f3c-3720789f0db4.png">

https://zpl.io/aRznzAz
https://zpl.io/VOdMmk1
https://zpl.io/b6DR3MK

**Comment by esengulov** [comment]
> <img alt="Screen Shot 2019-07-09 at 5 28 06 PM" width="1184" src="https://user-images.githubusercontent.com/42367908/60884546-eeeb2180-a26e-11e9-9f3c-3720789f0db4.png">
> 
> https://zpl.io/aRznzAz
> https://zpl.io/VOdMmk1
> https://zpl.io/b6DR3MK

@Dianaaiym this is the finalized controller in English, feel free to localize it
