### ISSUE TITLE
Constraints are breaking on Balance module

### ISSUE THREAD

**Issue by ealymbaev** [horizontalsystems/unstoppable-wallet-ios#747]
Steps to reproduce:
- install "green" app
- enable several coins
- go to Manage Coins and disable all coins
- tap Done and see logs about breaking constraints

**Comment by mNizhurin** [comment]
Saw it one time. Can't reproduce anymore. Problem is in BarsProgressView

**Comment by ealymbaev** [comment]
Issue does not reproduce anymore.
