### ISSUE TITLE
Wallet Backup Enforcement protocol

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#750]
- [ ] If the state of the wallet is "not backed up" for the given coin. Then click on receive buttons should trigger controller that would require user to backup the wallet before s/he can proceed (see attached). Note: there can be case when the user has backed some keys but not the other ones. Such cases should be handled accordingly.

- [ ]  if wallet not backed up, don't display the  red exclamation mark on Settings tab bar icon. Since we are asking user to backup before funds can be received the red alert icon on tab bar becomes redundant. The exclamation mark should be removed only from settings icon but should remain in all other places(settings controller, security controller, manage keys).

- [ ] title : Backup Required 

- [ ] description text string: You need to backup the [key_name] key before you may receive [coin_name]. @Dianaaiym localize texts

![6521B903-93DA-4DCC-B987-13C4AE02B265](https://user-images.githubusercontent.com/8611762/61531624-32047c00-aa49-11e9-8ee8-d569d8a3b9ab.JPG)

- @TalgatNurdinov provide layout.

**Comment by TalgatNurdinov** [comment]
<img width="772" alt="Screen Shot 2019-07-26 at 3 51 53 PM" src="https://user-images.githubusercontent.com/42367908/61943466-4ef6fd00-afbd-11e9-9994-5f5d724b1c70.png">

https://zpl.io/V4zeD5J
https://zpl.io/V4zeD5J

**Comment by esengulov** [comment]
> <img alt="Screen Shot 2019-07-26 at 3 51 53 PM" width="772" src="https://user-images.githubusercontent.com/42367908/61943466-4ef6fd00-afbd-11e9-9994-5f5d724b1c70.png">
> 
> https://zpl.io/V4zeD5J
> https://zpl.io/V4zeD5J

@TalgatNurdinov
why not to use bottom controller (i.e. Receive)?
