### ISSUE TITLE
Integrate Binance blockchain

### ISSUE THREAD

**Issue by ealymbaev** [horizontalsystems/unstoppable-wallet-ios#757]

**Comment by esen** [comment]
> Fee is fixed for TRANSFER transactions

[0.000375 BNB](https://docs.binance.org/trading-spec.html#current-fees-table-on-mainnet)

**Comment by esen** [comment]
> Only 1 confirmation is enough for transaction

[https://docs.binance.org/faq.html#what-is-the-design-principle-of-binance-chain](https://docs.binance.org/faq.html#what-is-the-design-principle-of-binance-chain)

**Comment by esengulov** [comment]
this issue also includes support for Binance block explorer

https://dex.binance.org/api/v1/tx/BA5279132280AD48AA01AAF4AF37591C7409205898899EA76D81703799B3EB81?format=json

**Comment by ealymbaev** [comment]
Full Transaction Info does not show "fee" field correctly
