### ISSUE TITLE
Price Alerts (Push Notifications)

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#761]
**Activating Alerts:**

- [x] Settings tab: add new section to settings from where user can set the price change alerts.
-- title: Notifications (@Dianaaiym, localizable text)
- [x] Settings tab: display number of activated notifications on the right side of the cell. The number should be shown when the user has set the alerts.
- [x] click on Settings >> Alerts: opens a screen that lists all coins with an option to enable/disable alerts for the coin.
- [x] permission to show notification should be shown when user tries to enable pushes
- [x] if the coin is disabled and has set alerts then it should be set to Off.
- [x] when the user Turns Off (denies) notification from OS settings: show following text and "turn on" button.
> The notifications for Unstoppable Wallet app are disabled. You need to turn on Notifications and allow background app refresh in order to be able to receive price change alerts. (@Dianaaiym button text is localizable)
>
> Button (Turn On) (@Dianaaiym button text is localizable)
- [x] new: change the text on top section to (@Dianaaiym)
>Set price change alerts for the coins you would like to watch.
>
>You will be alerted when the change in price for the last 24 hours exceeds selected threshold.

**Push Behavior** 

- [ ] fetch price data once every 60 minutes
- [x] click on push should open open: 
-- lock screen if the pin lock is enabled on app level
-- balance tab if the pin lock is disabled
- [x] on app open dismiss/clear all pushes 

**Push Template:**

- [x] push look:
-- title: Unstoppable
-- icon: app icon
- [x] sounds: use standard system sound

**Push Texts:**

- [x] when one coin is UP (over 5%)
-- push subtitle: Bitcoin 🚀🌙
-- push body: Up 5% 😎

- [x] when one coin is UP (over 3%)
-- push subtitle: Bitcoin 🚀
-- push body: Up 3% 😉

- [x] when one coin is UP (over 2%)
-- push subtitle: Bitcoin 🚀
-- push body: Up 2% 🙂

- [x] when one coin is DOWN (over 5%)
-- push subtitle: Bitcoin 💔
-- push body: Down 5% 😩

- [x] when one coin is DOWN (over 3%)
-- push subtitle: Bitcoin 💔
-- push body: Down 3% 😧

- [x] when one coin is DOWN (over 2%)
-- push subtitle: Bitcoin 💔
-- push body: Down 2% 😔

- [x] when more than two coins is UP/DOWN: group all notifications into a single notification.
-- push subtitle: Notifications 📈📉 (@Dianaaiym, localizable text, should be same to 'Notifications' in Settings)
-- push body: list coins from up to down by value: [coin_symbol_1] up x%,  [coin_symbol_2] up y%, [coin_symbol_3] down z%, ... etc

- [x] @Dianaaiym: in push texts above there are only two localizable elements
-- up / down
-- Portfolio Notifications

**@TalgatNurdinov** 

Enable user to set price change alerts. There should be a section in settings from where wallet user able to configure price change alerts. It should list all coins with following options for each:

- alerts Off
- alert on 2% change
- alert on 3% change
- alert on 5% change

**Comment by TalgatNurdinov** [comment]
<img width="823" alt="Screen Shot 2019-09-19 at 3 59 17 PM" src="https://user-images.githubusercontent.com/42367908/65234466-73231600-daf6-11e9-84f6-dd13202ec953.png">

https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=3139%3A1215

**Comment by esengulov** [comment]
@Dianaaiym this feature is currently integrated. However we deliberately hid it from the interface because at the moment the push notifications are not working as expected on iOS. Unfortunately this is something beyond our control as it's up to the iOS to decide when the app can be awaken in the background. We could have bypassed this by implementing a centralized push service that would send awake triggers to the apps but we decide not to do that as that requires a centralized infrastructure
