### ISSUE TITLE
Manage Keys >> Unlink

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#769]
**Unlink Button**

- [x] if the key is not backed up then click on this button should trigger following alert with 'Backup' button. "You need to backup this key before you may unlink it." Clicking on Backup button would open the Backup (intro step) for that key. @Dianaaiym this alert should be localized 
- [x] @Dianaaiym following three text blocks should be localized as well
-- text1: This action will remove the [key_title] key (wallet) from this device.
-- text2: Coins that will be disabled: [same coin list as on the key cell on KEYs page]
-- text3: If you don't have a backup of this key you will loose the respective funds. 
- [x] redesign the controller that is shown on the click of this button (see below).
![IMG_1653](https://user-images.githubusercontent.com/8611762/61525507-63c21680-aa3a-11e9-9ff7-b41500985d36.JPG)

**Comment by esengulov** [comment]
> * if the key is not backed up then click on this button should trigger following alert with OK button. "You need to backup this key before you may unlink it."

we need a design for this alert @TalgatNurdinov

**Comment by Dianaaiym** [comment]
add title "Delete Key"
https://app.zeplin.io/project/5c7cbfa0db2d7d520bedb542/screen/5d3581ff989d7cb33d2f9b9c
