### ISSUE TITLE
Manage Keys >> minor text corrections

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#791]
- [x] On EOS KEY where only "EOS" coin symbol is shown change the text to "EOS, EOS tokens"

@Dianaaiym 

- [x] text block between page title and keys. 
"Anyone with access to your Keys can steal your wallet funds. Store keys safely and never show them to anyone. [2 line breaks] Backup each key to be able to restore funds if you loose or break your phone, or simply the wallet app gets deleted."

- [x] change button text from Unlink to Delete
- [x] Manage Keys >> Delete >> alert controller (change all occurrences of unlink to delete )
-- text1: This action will delete the [key_title] key (wallet) from this device.
-- text2: Coins that will be disabled: [same coin list as on the key cell on KEYs page]
-- text3: If you don't have a backup of this key you will loose the respective funds. 
-- title : Delete Key (localizable)
-- button title : Delete from Phone (localizable)

**Comment by TalgatNurdinov** [comment]
https://zpl.io/aMRqGxr

**Comment by Dianaaiym** [comment]
Add title "Delete Key"
https://app.zeplin.io/project/5c7cbfa0db2d7d520bedb542/screen/5d3581ff989d7cb33d2f9b9c
