### ISSUE TITLE
Security ideas/ features

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#794]
- [x] View only mode

    Only MPK would be required for the app to work in this mode. View only mode. Full read mode, no write mode.

- [x] Blur mode

    Blur mode that would hide all sensitive data with blurred overlay. Can be removed on demand from settings. Blures balance on home tab. Everything else stays same. Deactivation of blur takes x hours.  

 - [x] Unlock pin

    Randomize the keypad each time the PIN needs to be entered.
    
- [x] duress pin

**Comment by Peter-Mackey** [comment]
Add support for plausible deniability - allowing a user to input an alternative app passcode, to view an entirely seperate wallet.

Also, it should be technologically impossible to extract the master private key directly from the keychain, so if a device were to be infected with advanced state-sponsored malware (such as Pegasus), the master private key would be protected, up until at least the next app unlock. Implementing this securely with a simple 6 digit numeric app passcode, will be challenging.
