### ISSUE TITLE
'Sort by' menu options

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#860]
- [ ] sort menu icon should appear when there are 5 or more items on the screen.
- [x] remove 'default' option from sorting menu
- [x] always resort upon completed sync (when all coins are in synced state)
- [x] sort menu options:  
-- Name 
-- Value

**Comment by Dianaaiym** [comment]
sort menu icon should appear when there are 5 or more items on the screen.
Same requirements as for the Android client.
