### ISSUE TITLE
UI control for graphs/charts

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#869]
Implement UI control for displaying chart.

It should accept all input data in constructor (or be set later) and it should respect constraints.

**Comment by TalgatNurdinov** [comment]
<img width="1147" alt="Screen Shot 2019-08-16 at 10 40 07 AM" src="https://user-images.githubusercontent.com/42367908/63143874-3d2fd500-c012-11e9-839c-fb7a67b810f7.png">

https://app.zeplin.io/project/5c7cbfa0db2d7d520bedb542/dashboard?seid=5d5630a2152c905223c07f93
