### ISSUE TITLE
Display approx. transaction duration on Send

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#870]
The approximate duration can be calculated depending on:

- [x] (in progress) wait for the IPFS will also provide the duration along with each rate, https://github.com/horizontalsystems/blockchain-meta/issues/78
-  [x] apply new layout:
- remove slider and instead display "Transaction speed" row with only three options Slow, Medium, Fast in drop-down menu. Default "Medium"
- unlike the fee amount, the transaction speed value should be visible even before the user enters any amount input. 
- in cases where blockchain doesn't have TX fees and transactions are instant, the duration should be shown as "instant"
- [ ] transaction duration wording
-- in 'transaction speed' selector menu display values with ~ (ex: ~4 hours)
-- on send controller the values should be shows as "within 4 hours"

@TalgatNurdinov

- [x]  please upload designs
- send controller (for BTC)
- send controller (for EOS)
- send controller (for Dash)
- speed selector menu
- confirmation controller

@Dianaaiym 

- [x] the texts below should be localized
- transaction speed
- slow / medium /  fast
- instant 
- [ ] the word "within" should be localized as well 
-- Russian: в течении 1ч.

[Provide approximate time before inclusion in block](https://github.com/horizontalsystems/blockchain-fee-rate-kit-ios/issues/9)

**Comment by TalgatNurdinov** [comment]
<img width="1153" alt="Screen Shot 2019-08-16 at 10 24 29 AM" src="https://user-images.githubusercontent.com/42367908/63143464-356f3100-c010-11e9-958c-252c90b80ba1.png">
<img width="1152" alt="Screen Shot 2019-08-16 at 10 25 21 AM" src="https://user-images.githubusercontent.com/42367908/63143474-491a9780-c010-11e9-849e-bfc402c240f0.png">

https://app.zeplin.io/project/5c7cbfa0db2d7d520bedb542/dashboard?seid=5d416c247407042bc3c9f1ff
