### ISSUE TITLE
Add: Settings >> Report A Problem

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#871]
We need to enable users to send bug reports to our email and/or Telegram group
@TalgatNurdinov we need a look for this one as well

- Telegram group link https://t.me/joinchat/AL69MRcUAqCaEBLCnHUsQw
- email should open default mail app if such exists

**Comment by TalgatNurdinov** [comment]
<img width="380" alt="Screen Shot 2019-08-15 at 3 10 05 PM" src="https://user-images.githubusercontent.com/42367908/63085269-f0df8900-bf6e-11e9-8097-712a36acaae0.png">

https://zpl.io/2y6g6WK

**Comment by esengulov** [comment]
> <img alt="Screen Shot 2019-08-15 at 3 10 05 PM" width="380" src="https://user-images.githubusercontent.com/42367908/63085269-f0df8900-bf6e-11e9-8097-712a36acaae0.png">
> 
> https://zpl.io/2y6g6WK

include destination page please :)

**Comment by TalgatNurdinov** [comment]
https://zpl.io/ag6oBLQ
