### ISSUE TITLE
Consistent usage of 'Cancel' text & 'Cancel' icon

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#910]
- [x] Cancel icon should appear on all bottom controllers: 
- graph view
- create key 
- delete key
- transaction info
- receive

- [x] Cancel text should appear on all full screen presenters
- send controller
- full transaction info

**Comment by esengulov** [comment]
@TalgatNurdinov need design guidelines

**Comment by TalgatNurdinov** [comment]
<img width="1987" alt="Screen Shot 2019-08-22 at 3 48 45 PM" src="https://user-images.githubusercontent.com/42367908/63504904-5940e400-c4f4-11e9-9b77-701801aa1917.png">

receive - https://zpl.io/2p4LB9y
tx info - https://zpl.io/adpYJ3L
delete key - https://zpl.io/aMRqGxr
create key - https://zpl.io/a3Rq8k8
create key - https://zpl.io/25AGOWj

**Comment by TalgatNurdinov** [comment]
<img width="1155" alt="Screen Shot 2019-08-22 at 3 55 47 PM" src="https://user-images.githubusercontent.com/42367908/63505407-54306480-c4f5-11e9-93d0-c1c1bb7deabd.png">

Send - https://zpl.io/V1957B4
Tx Full Info - https://zpl.io/am53woK

**Comment by Dianaaiym** [comment]
Cancel icon not appear on graph view controller
