### ISSUE TITLE
TX info : Outgoing Transactions should display fee

### ISSUE THREAD

**Issue by horsys** [horizontalsystems/unstoppable-wallet-ios#918]
- [x] Outgoing transactions should display fee in tx info controller.
- [x] The fee should be shown in the coin that was used for the fee. in other words the ERC20 tokens will have fee shown in ETH.

outgoing transactions to your own address:

- [x] should have asterisk icon after the amount (ex: 0.00*)
- [x] there should be an extra field/cell at the bottom of controller that would show:

> * The value of this transaction appears as 0 because it was sent to your own address

- [ ] @Dianaaiym the text above should be localized

[bitcoin-kit-ios: Add fee to TransactionInfo](https://github.com/horizontalsystems/bitcoin-kit-ios/issues/416)

**Comment by esen** [comment]
#928 ticket is the continuation of this ticket
