### ISSUE TITLE
Chart design changes

### ISSUE THREAD

**Issue by TalgatNurdinov** [horizontalsystems/unstoppable-wallet-ios#950]
- [x] Price changes in precent by default
- [x] Time stamp logic: Hide hours / minutes on 6m/1y chart in pressed state
- [x] New tabs
- [x] Change M.Cap / 52 wk values font size
- [x] Rename 1w to 7d
- [x] Add space between number and sign (-+) in price change
- [x] M.Cap value should be show in 3 symbols (96.8 B)

<img width="765" alt="Screen Shot 2019-08-26 at 4 56 57 PM" src="https://user-images.githubusercontent.com/42367908/63685977-8823c680-c822-11e9-8340-8c121b1c9906.png">

**Comment by TalgatNurdinov** [comment]
- [ ] Swap places of price and date in selected state
- [ ]  M.Cap value should be show in 3 symbols (96.8 B)

**Comment by esengulov** [comment]
not all requested changes were implemented
