### ISSUE TITLE
Layout Changes for Welcome >> New

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/unstoppable-wallet-ios#996]
- [x] apply new layout for wallet creation: welcome >> new wallet (use attached image for reference. Find the actual layout/specs on Figma)
- [x] user is expected to select one coin. After click on the coin s/he will be taken to the balance tab with the coin activated.
- [x] order of coins: Bitcoin, Ethereum, Bitcoin Cash, Dash, BNB, EOS
- [x] EOS coin. show error when user tries to click on the EOS. Same error that's shown on coin manager >> EOS > create action.

@Dianaaiym 

 - [ ] the text at the top of the controller needs to be localized. 

> Select one cryptocurrency to start. You will be able to add other cryptocurrencies later.

**Comment by TalgatNurdinov** [comment]
<img width="775" alt="Screen Shot 2019-09-10 at 6 06 51 PM" src="https://user-images.githubusercontent.com/42367908/64612662-23f22c80-d3f6-11e9-8fda-f1190227bada.png">

https://www.figma.com/file/p8oB6wTgeqJihiN2l87A3n/Unstoppable-Design-System?node-id=2886%3A2609
